// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: applications.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countApplicationsForVacancy = `-- name: CountApplicationsForVacancy :one
SELECT count(*)::bigint FROM applications WHERE vacancy_id = $1 AND status <> 'withdrawn'
`

// Сколько откликов человек отправил за окно (ограничение частоты считается по rate_events, это для проверок).
func (q *Queries) CountApplicationsForVacancy(ctx context.Context, vacancyID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countApplicationsForVacancy, vacancyID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countMyApplications = `-- name: CountMyApplications :one
SELECT count(*)::bigint FROM applications WHERE user_id = $1
`

func (q *Queries) CountMyApplications(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMyApplications, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getActiveApplicationForVacancy = `-- name: GetActiveApplicationForVacancy :one
SELECT id, status FROM applications WHERE vacancy_id = $1 AND user_id = $2 AND status <> 'withdrawn'
`

type GetActiveApplicationForVacancyParams struct {
	VacancyID uuid.UUID
	UserID    uuid.UUID
}

type GetActiveApplicationForVacancyRow struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) GetActiveApplicationForVacancy(ctx context.Context, arg GetActiveApplicationForVacancyParams) (GetActiveApplicationForVacancyRow, error) {
	row := q.db.QueryRow(ctx, getActiveApplicationForVacancy, arg.VacancyID, arg.UserID)
	var i GetActiveApplicationForVacancyRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const getApplication = `-- name: GetApplication :one
SELECT a.id, a.vacancy_id, a.user_id, a.status, a.cover_letter, a.contact_email, a.profile, a.decision_note,
       a.created_at, a.updated_at, a.status_changed_at,
       u.display_name AS applicant_name,
       v.title AS vacancy_title, v.status AS vacancy_status, v.org_id, v.unit_id, v.org_name, v.org_slug, v.deadline
FROM applications a
JOIN users u ON u.id = a.user_id
JOIN vacancy_view v ON v.id = a.vacancy_id
WHERE a.id = $1
`

type GetApplicationRow struct {
	ID              uuid.UUID
	VacancyID       uuid.UUID
	UserID          uuid.UUID
	Status          string
	CoverLetter     string
	ContactEmail    string
	Profile         []byte
	DecisionNote    string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	StatusChangedAt time.Time
	ApplicantName   string
	VacancyTitle    string
	VacancyStatus   string
	OrgID           uuid.UUID
	UnitID          *uuid.UUID
	OrgName         string
	OrgSlug         string
	Deadline        *time.Time
}

// Карточка отклика с вакансией и именем соискателя.
func (q *Queries) GetApplication(ctx context.Context, id uuid.UUID) (GetApplicationRow, error) {
	row := q.db.QueryRow(ctx, getApplication, id)
	var i GetApplicationRow
	err := row.Scan(
		&i.ID,
		&i.VacancyID,
		&i.UserID,
		&i.Status,
		&i.CoverLetter,
		&i.ContactEmail,
		&i.Profile,
		&i.DecisionNote,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StatusChangedAt,
		&i.ApplicantName,
		&i.VacancyTitle,
		&i.VacancyStatus,
		&i.OrgID,
		&i.UnitID,
		&i.OrgName,
		&i.OrgSlug,
		&i.Deadline,
	)
	return i, err
}

const getApplicationFile = `-- name: GetApplicationFile :one
SELECT id, reference_id, kind, name, size, data FROM application_files WHERE id = $1 AND application_id = $2
`

type GetApplicationFileParams struct {
	ID            uuid.UUID
	ApplicationID uuid.UUID
}

type GetApplicationFileRow struct {
	ID          uuid.UUID
	ReferenceID *uuid.UUID
	Kind        string
	Name        string
	Size        int32
	Data        []byte
}

func (q *Queries) GetApplicationFile(ctx context.Context, arg GetApplicationFileParams) (GetApplicationFileRow, error) {
	row := q.db.QueryRow(ctx, getApplicationFile, arg.ID, arg.ApplicationID)
	var i GetApplicationFileRow
	err := row.Scan(
		&i.ID,
		&i.ReferenceID,
		&i.Kind,
		&i.Name,
		&i.Size,
		&i.Data,
	)
	return i, err
}

const getVacancyForApply = `-- name: GetVacancyForApply :one

SELECT id, org_id, unit_id, status, title, deadline, org_name, org_slug FROM vacancy_view WHERE id = $1
`

type GetVacancyForApplyRow struct {
	ID       uuid.UUID
	OrgID    uuid.UUID
	UnitID   *uuid.UUID
	Status   string
	Title    string
	Deadline *time.Time
	OrgName  string
	OrgSlug  string
}

// Отклики (срез 8).
// Всё о вакансии, что нужно для отклика и для проверки прав.
func (q *Queries) GetVacancyForApply(ctx context.Context, id uuid.UUID) (GetVacancyForApplyRow, error) {
	row := q.db.QueryRow(ctx, getVacancyForApply, id)
	var i GetVacancyForApplyRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UnitID,
		&i.Status,
		&i.Title,
		&i.Deadline,
		&i.OrgName,
		&i.OrgSlug,
	)
	return i, err
}

const insertApplication = `-- name: InsertApplication :one
INSERT INTO applications (vacancy_id, user_id, cover_letter, contact_email, profile, created_at, updated_at, status_changed_at)
VALUES ($1, $2, $3, $4, $5, $6, $6, $6)
RETURNING id
`

type InsertApplicationParams struct {
	VacancyID    uuid.UUID
	UserID       uuid.UUID
	CoverLetter  string
	ContactEmail string
	Profile      []byte
	Now          time.Time
}

func (q *Queries) InsertApplication(ctx context.Context, arg InsertApplicationParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertApplication,
		arg.VacancyID,
		arg.UserID,
		arg.CoverLetter,
		arg.ContactEmail,
		arg.Profile,
		arg.Now,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertApplicationFile = `-- name: InsertApplicationFile :one
INSERT INTO application_files (application_id, reference_id, kind, name, size, position, data, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type InsertApplicationFileParams struct {
	ApplicationID uuid.UUID
	ReferenceID   *uuid.UUID
	Kind          string
	Name          string
	Size          int32
	Position      int16
	Data          []byte
	Now           time.Time
}

func (q *Queries) InsertApplicationFile(ctx context.Context, arg InsertApplicationFileParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertApplicationFile,
		arg.ApplicationID,
		arg.ReferenceID,
		arg.Kind,
		arg.Name,
		arg.Size,
		arg.Position,
		arg.Data,
		arg.Now,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listApplicationFiles = `-- name: ListApplicationFiles :many
SELECT id, reference_id, kind, name, size, position FROM application_files WHERE application_id = $1 ORDER BY kind, position, created_at
`

type ListApplicationFilesRow struct {
	ID          uuid.UUID
	ReferenceID *uuid.UUID
	Kind        string
	Name        string
	Size        int32
	Position    int16
}

// Список файлов без содержимого.
func (q *Queries) ListApplicationFiles(ctx context.Context, applicationID uuid.UUID) ([]ListApplicationFilesRow, error) {
	rows, err := q.db.Query(ctx, listApplicationFiles, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApplicationFilesRow
	for rows.Next() {
		var i ListApplicationFilesRow
		if err := rows.Scan(
			&i.ID,
			&i.ReferenceID,
			&i.Kind,
			&i.Name,
			&i.Size,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyApplications = `-- name: ListMyApplications :many
SELECT a.id, a.status, a.created_at, a.status_changed_at,
       v.id AS vacancy_id, v.title AS vacancy_title, v.status AS vacancy_status, v.org_name, v.org_slug, v.deadline, v.city AS vacancy_city,
       (SELECT count(*) FROM reference_requests r WHERE r.application_id = a.id)::bigint AS refs_total,
       (SELECT count(*) FROM reference_requests r WHERE r.application_id = a.id AND r.status = 'received')::bigint AS refs_received,
       (SELECT count(*) FROM application_invitations i WHERE i.application_id = a.id AND i.status = 'pending')::bigint AS invites_pending
FROM applications a
JOIN vacancy_view v ON v.id = a.vacancy_id
WHERE a.user_id = $1
ORDER BY a.created_at DESC, a.id
LIMIT $3 OFFSET $2
`

type ListMyApplicationsParams struct {
	UserID uuid.UUID
	Off    int32
	Lim    int32
}

type ListMyApplicationsRow struct {
	ID              uuid.UUID
	Status          string
	CreatedAt       time.Time
	StatusChangedAt time.Time
	VacancyID       uuid.UUID
	VacancyTitle    string
	VacancyStatus   string
	OrgName         string
	OrgSlug         string
	Deadline        *time.Time
	VacancyCity     string
	RefsTotal       int64
	RefsReceived    int64
	InvitesPending  int64
}

// «Мои отклики»: новые сверху, с числом рекомендаций.
func (q *Queries) ListMyApplications(ctx context.Context, arg ListMyApplicationsParams) ([]ListMyApplicationsRow, error) {
	rows, err := q.db.Query(ctx, listMyApplications, arg.UserID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMyApplicationsRow
	for rows.Next() {
		var i ListMyApplicationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.CreatedAt,
			&i.StatusChangedAt,
			&i.VacancyID,
			&i.VacancyTitle,
			&i.VacancyStatus,
			&i.OrgName,
			&i.OrgSlug,
			&i.Deadline,
			&i.VacancyCity,
			&i.RefsTotal,
			&i.RefsReceived,
			&i.InvitesPending,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgMemberIDs = `-- name: ListOrgMemberIDs :many
SELECT user_id FROM org_members WHERE org_id = $1 ORDER BY joined_at, user_id
`

// Сотрудники организации (для рассылки уведомлений тем, кто видит отклики).
func (q *Queries) ListOrgMemberIDs(ctx context.Context, orgID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listOrgMemberIDs, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setApplicationStatusFrom = `-- name: SetApplicationStatusFrom :execrows
UPDATE applications SET status = $1, updated_at = $2, status_changed_at = $2
WHERE id = $3 AND status = ANY($4::text[])
`

type SetApplicationStatusFromParams struct {
	ToStatus     string
	Now          time.Time
	ID           uuid.UUID
	FromStatuses []string
}

// Статус меняется только из ожидаемых: две одновременные смены не пройдут обе.
func (q *Queries) SetApplicationStatusFrom(ctx context.Context, arg SetApplicationStatusFromParams) (int64, error) {
	result, err := q.db.Exec(ctx, setApplicationStatusFrom,
		arg.ToStatus,
		arg.Now,
		arg.ID,
		arg.FromStatuses,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
