// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_tokens.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumeAuthToken = `-- name: ConsumeAuthToken :one
UPDATE auth_tokens SET used_at = $1::timestamptz
WHERE token_hash = $2 AND purpose = $3
  AND used_at IS NULL AND expires_at > $1::timestamptz
RETURNING user_id
`

type ConsumeAuthTokenParams struct {
	Now       time.Time
	TokenHash []byte
	Purpose   string
}

// Ссылка одноразовая: проверка и «погашение» одним запросом, чтобы два одновременных запроса не прошли оба.
func (q *Queries) ConsumeAuthToken(ctx context.Context, arg ConsumeAuthTokenParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, consumeAuthToken, arg.Now, arg.TokenHash, arg.Purpose)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const createAuthToken = `-- name: CreateAuthToken :exec
INSERT INTO auth_tokens (user_id, purpose, token_hash, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateAuthTokenParams struct {
	UserID    uuid.UUID
	Purpose   string
	TokenHash []byte
	CreatedAt time.Time
	ExpiresAt time.Time
}

func (q *Queries) CreateAuthToken(ctx context.Context, arg CreateAuthTokenParams) error {
	_, err := q.db.Exec(ctx, createAuthToken,
		arg.UserID,
		arg.Purpose,
		arg.TokenHash,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredAuthTokens = `-- name: DeleteExpiredAuthTokens :exec
DELETE FROM auth_tokens WHERE expires_at <= $1
`

func (q *Queries) DeleteExpiredAuthTokens(ctx context.Context, expiresAt time.Time) error {
	_, err := q.db.Exec(ctx, deleteExpiredAuthTokens, expiresAt)
	return err
}

const latestAuthTokenAt = `-- name: LatestAuthTokenAt :one
SELECT COALESCE(max(created_at), 'epoch'::timestamptz)::timestamptz AS at
FROM auth_tokens WHERE user_id = $1 AND purpose = $2
`

type LatestAuthTokenAtParams struct {
	UserID  uuid.UUID
	Purpose string
}

// Когда последний раз выдавали ссылку этого назначения (пауза между письмами).
func (q *Queries) LatestAuthTokenAt(ctx context.Context, arg LatestAuthTokenAtParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, latestAuthTokenAt, arg.UserID, arg.Purpose)
	var at time.Time
	err := row.Scan(&at)
	return at, err
}

const peekAuthToken = `-- name: PeekAuthToken :one
SELECT u.id AS user_id, u.email
FROM auth_tokens t JOIN users u ON u.id = t.user_id
WHERE t.token_hash = $1 AND t.purpose = $2
  AND t.used_at IS NULL AND t.expires_at > $3::timestamptz
`

type PeekAuthTokenParams struct {
	TokenHash []byte
	Purpose   string
	Now       time.Time
}

type PeekAuthTokenRow struct {
	UserID uuid.UUID
	Email  string
}

// Посмотреть ссылку, не погашая её (чтобы проверить новый пароль до того, как ссылка сгорит).
func (q *Queries) PeekAuthToken(ctx context.Context, arg PeekAuthTokenParams) (PeekAuthTokenRow, error) {
	row := q.db.QueryRow(ctx, peekAuthToken, arg.TokenHash, arg.Purpose, arg.Now)
	var i PeekAuthTokenRow
	err := row.Scan(&i.UserID, &i.Email)
	return i, err
}

const supersedeAuthTokens = `-- name: SupersedeAuthTokens :exec
UPDATE auth_tokens SET used_at = $1::timestamptz
WHERE user_id = $2 AND purpose = $3 AND used_at IS NULL
`

type SupersedeAuthTokensParams struct {
	At      time.Time
	UserID  uuid.UUID
	Purpose string
}

// Старые неиспользованные ссылки того же назначения перестают работать.
func (q *Queries) SupersedeAuthTokens(ctx context.Context, arg SupersedeAuthTokensParams) error {
	_, err := q.db.Exec(ctx, supersedeAuthTokens, arg.At, arg.UserID, arg.Purpose)
	return err
}
