// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health.sql

package dbgen

import (
	"context"
)

const serverVersion = `-- name: ServerVersion :one
SELECT current_setting('server_version')::text AS server_version
`

func (q *Queries) ServerVersion(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, serverVersion)
	var server_version string
	err := row.Scan(&server_version)
	return server_version, err
}
