// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invitations.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumeInvitation = `-- name: ConsumeInvitation :one
UPDATE org_invitations SET accepted_at = $1::timestamptz
WHERE token_hash = $2 AND accepted_at IS NULL AND revoked_at IS NULL AND expires_at > $1::timestamptz
RETURNING id, org_id, role, unit_id, email::text AS email
`

type ConsumeInvitationParams struct {
	Now       time.Time
	TokenHash []byte
}

type ConsumeInvitationRow struct {
	ID     uuid.UUID
	OrgID  uuid.UUID
	Role   string
	UnitID *uuid.UUID
	Email  string
}

// Принять приглашение по ссылке: «гашение» одним запросом, чтобы две одновременные попытки не прошли обе.
func (q *Queries) ConsumeInvitation(ctx context.Context, arg ConsumeInvitationParams) (ConsumeInvitationRow, error) {
	row := q.db.QueryRow(ctx, consumeInvitation, arg.Now, arg.TokenHash)
	var i ConsumeInvitationRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Role,
		&i.UnitID,
		&i.Email,
	)
	return i, err
}

const consumeInvitationByID = `-- name: ConsumeInvitationByID :one
UPDATE org_invitations SET accepted_at = $1::timestamptz
WHERE id = $2 AND accepted_at IS NULL AND revoked_at IS NULL AND expires_at > $1::timestamptz
RETURNING id, org_id, role, unit_id, email::text AS email
`

type ConsumeInvitationByIDParams struct {
	Now time.Time
	ID  uuid.UUID
}

type ConsumeInvitationByIDRow struct {
	ID     uuid.UUID
	OrgID  uuid.UUID
	Role   string
	UnitID *uuid.UUID
	Email  string
}

// То же по номеру приглашения: так принимают приглашение из списка «Мои приглашения», где ссылки нет.
func (q *Queries) ConsumeInvitationByID(ctx context.Context, arg ConsumeInvitationByIDParams) (ConsumeInvitationByIDRow, error) {
	row := q.db.QueryRow(ctx, consumeInvitationByID, arg.Now, arg.ID)
	var i ConsumeInvitationByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Role,
		&i.UnitID,
		&i.Email,
	)
	return i, err
}

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO org_invitations (org_id, email, role, unit_id, token_hash, invited_by, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type CreateInvitationParams struct {
	OrgID     uuid.UUID
	Email     string
	Role      string
	UnitID    *uuid.UUID
	TokenHash []byte
	InvitedBy *uuid.UUID
	CreatedAt time.Time
	ExpiresAt time.Time
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.OrgID,
		arg.Email,
		arg.Role,
		arg.UnitID,
		arg.TokenHash,
		arg.InvitedBy,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteOldInvitations = `-- name: DeleteOldInvitations :exec
DELETE FROM org_invitations WHERE expires_at <= $1
`

// Приглашения, срок которых вышел давно (before), больше не нужны.
func (q *Queries) DeleteOldInvitations(ctx context.Context, expiresAt time.Time) error {
	_, err := q.db.Exec(ctx, deleteOldInvitations, expiresAt)
	return err
}

const listInvitationsForEmail = `-- name: ListInvitationsForEmail :many
SELECT i.id, i.role, i.unit_id, un.name AS unit_name, o.slug AS org_slug, o.name AS org_name, i.created_at, i.expires_at
FROM org_invitations i
JOIN organizations o ON o.id = i.org_id
LEFT JOIN units un ON un.id = i.unit_id
WHERE i.email = $1 AND i.accepted_at IS NULL AND i.revoked_at IS NULL AND i.expires_at > $2::timestamptz
ORDER BY i.created_at DESC, i.id
`

type ListInvitationsForEmailParams struct {
	Email string
	Now   time.Time
}

type ListInvitationsForEmailRow struct {
	ID        uuid.UUID
	Role      string
	UnitID    *uuid.UUID
	UnitName  *string
	OrgSlug   string
	OrgName   string
	CreatedAt time.Time
	ExpiresAt time.Time
}

// Живые приглашения на почту человека (показываем их ему в «Организации», не только в письме).
func (q *Queries) ListInvitationsForEmail(ctx context.Context, arg ListInvitationsForEmailParams) ([]ListInvitationsForEmailRow, error) {
	rows, err := q.db.Query(ctx, listInvitationsForEmail, arg.Email, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInvitationsForEmailRow
	for rows.Next() {
		var i ListInvitationsForEmailRow
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.UnitID,
			&i.UnitName,
			&i.OrgSlug,
			&i.OrgName,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingInvitations = `-- name: ListPendingInvitations :many
SELECT i.id, i.email::text AS email, i.role, i.unit_id, un.name AS unit_name, i.created_at, i.expires_at
FROM org_invitations i LEFT JOIN units un ON un.id = i.unit_id
WHERE i.org_id = $1 AND i.accepted_at IS NULL AND i.revoked_at IS NULL AND i.expires_at > $2::timestamptz
ORDER BY i.created_at DESC, i.id
`

type ListPendingInvitationsParams struct {
	OrgID uuid.UUID
	Now   time.Time
}

type ListPendingInvitationsRow struct {
	ID        uuid.UUID
	Email     string
	Role      string
	UnitID    *uuid.UUID
	UnitName  *string
	CreatedAt time.Time
	ExpiresAt time.Time
}

func (q *Queries) ListPendingInvitations(ctx context.Context, arg ListPendingInvitationsParams) ([]ListPendingInvitationsRow, error) {
	rows, err := q.db.Query(ctx, listPendingInvitations, arg.OrgID, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingInvitationsRow
	for rows.Next() {
		var i ListPendingInvitationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Role,
			&i.UnitID,
			&i.UnitName,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const peekInvitation = `-- name: PeekInvitation :one
SELECT i.id, i.org_id, i.email::text AS email, i.role, i.unit_id, un.name AS unit_name,
       o.slug AS org_slug, o.name AS org_name
FROM org_invitations i
JOIN organizations o ON o.id = i.org_id
LEFT JOIN units un ON un.id = i.unit_id
WHERE i.token_hash = $1 AND i.accepted_at IS NULL AND i.revoked_at IS NULL AND i.expires_at > $2::timestamptz
`

type PeekInvitationParams struct {
	TokenHash []byte
	Now       time.Time
}

type PeekInvitationRow struct {
	ID       uuid.UUID
	OrgID    uuid.UUID
	Email    string
	Role     string
	UnitID   *uuid.UUID
	UnitName *string
	OrgSlug  string
	OrgName  string
}

// Посмотреть живое приглашение по ссылке, не принимая его.
func (q *Queries) PeekInvitation(ctx context.Context, arg PeekInvitationParams) (PeekInvitationRow, error) {
	row := q.db.QueryRow(ctx, peekInvitation, arg.TokenHash, arg.Now)
	var i PeekInvitationRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.Role,
		&i.UnitID,
		&i.UnitName,
		&i.OrgSlug,
		&i.OrgName,
	)
	return i, err
}

const revokeInvitation = `-- name: RevokeInvitation :execrows
UPDATE org_invitations SET revoked_at = $1::timestamptz
WHERE id = $2 AND org_id = $3 AND accepted_at IS NULL AND revoked_at IS NULL
`

type RevokeInvitationParams struct {
	At    time.Time
	ID    uuid.UUID
	OrgID uuid.UUID
}

func (q *Queries) RevokeInvitation(ctx context.Context, arg RevokeInvitationParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeInvitation, arg.At, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokePendingInvitations = `-- name: RevokePendingInvitations :exec
UPDATE org_invitations SET revoked_at = $1::timestamptz
WHERE org_id = $2 AND email = $3 AND accepted_at IS NULL AND revoked_at IS NULL
`

type RevokePendingInvitationsParams struct {
	At    time.Time
	OrgID uuid.UUID
	Email string
}

// Новое приглашение той же почте отменяет прежние, ещё не принятые.
func (q *Queries) RevokePendingInvitations(ctx context.Context, arg RevokePendingInvitationsParams) error {
	_, err := q.db.Exec(ctx, revokePendingInvitations, arg.At, arg.OrgID, arg.Email)
	return err
}
