// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: journals.sql

package dbgen

import (
	"context"
	"time"
)

const clearJournals = `-- name: ClearJournals :exec
DELETE FROM journals
`

func (q *Queries) ClearJournals(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearJournals)
	return err
}

const journalsByISSN = `-- name: JournalsByISSN :many
SELECT x.issn, j.id, j.title, j.quartile, j.data_year
FROM journal_issns x JOIN journals j ON j.id = x.journal_id
WHERE x.issn = ANY($1::text[])
`

type JournalsByISSNRow struct {
	Issn     string
	ID       int64
	Title    string
	Quartile *int16
	DataYear int16
}

// Журналы по ISSN публикаций (профиль, найденная по DOI работа).
func (q *Queries) JournalsByISSN(ctx context.Context, issns []string) ([]JournalsByISSNRow, error) {
	rows, err := q.db.Query(ctx, journalsByISSN, issns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JournalsByISSNRow
	for rows.Next() {
		var i JournalsByISSNRow
		if err := rows.Scan(
			&i.Issn,
			&i.ID,
			&i.Title,
			&i.Quartile,
			&i.DataYear,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const journalsEdition = `-- name: JournalsEdition :one

SELECT edition FROM reference_sources WHERE catalog = 'journals'
`

// Справочник журналов (срез 14). Строки грузит internal/journals (COPY), здесь чтение и служебное.
// Какой выпуск справочника загружен (нет строки — справочник пуст).
func (q *Queries) JournalsEdition(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, journalsEdition)
	var edition string
	err := row.Scan(&edition)
	return edition, err
}

const saveJournalsSource = `-- name: SaveJournalsSource :exec
INSERT INTO reference_sources (catalog, title, url, edition, checked_on)
VALUES ('journals', $1, $2, $3, $4)
ON CONFLICT (catalog) DO UPDATE
SET title = EXCLUDED.title, url = EXCLUDED.url, edition = EXCLUDED.edition, checked_on = EXCLUDED.checked_on
`

type SaveJournalsSourceParams struct {
	Title     string
	Url       string
	Edition   string
	CheckedOn time.Time
}

func (q *Queries) SaveJournalsSource(ctx context.Context, arg SaveJournalsSourceParams) error {
	_, err := q.db.Exec(ctx, saveJournalsSource,
		arg.Title,
		arg.Url,
		arg.Edition,
		arg.CheckedOn,
	)
	return err
}

const searchJournals = `-- name: SearchJournals :many
SELECT j.id, j.title, j.publisher, j.quartile, j.data_year,
       (SELECT array_agg(x.issn ORDER BY x.position) FROM journal_issns x WHERE x.journal_id = j.id)::text[] AS issns
FROM journals j
WHERE CASE WHEN $1::text <> ''
        THEN EXISTS (SELECT 1 FROM journal_issns x WHERE x.journal_id = j.id AND x.issn = $1::text)
        ELSE j.title ILIKE ALL ($2::text[]) AND EXISTS (SELECT 1 FROM journal_issns x WHERE x.journal_id = j.id) END
ORDER BY lower(j.title) = lower($3::text) DESC, j.title ILIKE $4::text DESC, j.sjr DESC NULLS LAST, j.title, j.id
LIMIT $5
`

type SearchJournalsParams struct {
	Issn     string
	Patterns []string
	Q        string
	Prefix   string
	RowLimit int32
}

type SearchJournalsRow struct {
	ID        int64
	Title     string
	Publisher string
	Quartile  *int16
	DataYear  int16
	Issns     []string
}

// Поиск журнала для формы публикации: по ISSN (@issn) или по словам названия (@patterns: каждое слово «%слово%»).
// Сначала точное название, потом начинающиеся с запроса, потом по SJR. Журналы без ISSN в справочник не попадают.
func (q *Queries) SearchJournals(ctx context.Context, arg SearchJournalsParams) ([]SearchJournalsRow, error) {
	rows, err := q.db.Query(ctx, searchJournals,
		arg.Issn,
		arg.Patterns,
		arg.Q,
		arg.Prefix,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchJournalsRow
	for rows.Next() {
		var i SearchJournalsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Publisher,
			&i.Quartile,
			&i.DataYear,
			&i.Issns,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
