// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: landing.sql

package dbgen

import (
	"context"
	"time"
)

const landingCounts = `-- name: LandingCounts :one

SELECT
  (SELECT count(*) FROM vacancies v
    WHERE v.status = 'published' AND (v.deadline IS NULL OR v.deadline >= $1::date))::bigint AS open_vacancies,
  (SELECT count(DISTINCT v.org_id) FROM vacancies v
    WHERE v.status = 'published' AND (v.deadline IS NULL OR v.deadline >= $1::date))::bigint AS hiring_organizations,
  (SELECT count(*) FROM profiles p
    WHERE p.visibility = ANY($2::text[]) AND p.headline <> '')::bigint AS scientists
`

type LandingCountsParams struct {
	Today time.Time
	Modes []string
}

type LandingCountsRow struct {
	OpenVacancies       int64
	HiringOrganizations int64
	Scientists          int64
}

// Числа для главной страницы (срез 12). «Открытая» вакансия — опубликованная, срок подачи которой не прошёл (today — сегодня по Москве),
// то есть та же, что находит поиск (D-066).
func (q *Queries) LandingCounts(ctx context.Context, arg LandingCountsParams) (LandingCountsRow, error) {
	row := q.db.QueryRow(ctx, landingCounts, arg.Today, arg.Modes)
	var i LandingCountsRow
	err := row.Scan(&i.OpenVacancies, &i.HiringOrganizations, &i.Scientists)
	return i, err
}

const landingVacanciesByField = `-- name: LandingVacanciesByField :many
SELECT f.field_code, f.vacancies
FROM (
  SELECT split_part(vs.specialty_code, '.', 1)::text AS field_code, count(DISTINCT v.id)::bigint AS vacancies
  FROM vacancies v JOIN vacancy_specialties vs ON vs.vacancy_id = v.id
  WHERE v.status = 'published' AND (v.deadline IS NULL OR v.deadline >= $1::date)
  GROUP BY 1
) f
ORDER BY f.field_code::int
`

type LandingVacanciesByFieldRow struct {
	FieldCode string
	Vacancies int64
}

// Открытые вакансии по областям науки. Вакансия с несколькими специальностями одной области считается один раз,
// а со специальностями разных областей — в каждой.
func (q *Queries) LandingVacanciesByField(ctx context.Context, today time.Time) ([]LandingVacanciesByFieldRow, error) {
	rows, err := q.db.Query(ctx, landingVacanciesByField, today)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LandingVacanciesByFieldRow
	for rows.Next() {
		var i LandingVacanciesByFieldRow
		if err := rows.Scan(&i.FieldCode, &i.Vacancies); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const landingVacanciesByType = `-- name: LandingVacanciesByType :many
SELECT p.position_type AS position_type, count(*)::bigint AS vacancies
FROM vacancies v JOIN positions p ON p.code = v.position_code
WHERE v.status = 'published' AND (v.deadline IS NULL OR v.deadline >= $1::date)
GROUP BY 1
ORDER BY 1
`

type LandingVacanciesByTypeRow struct {
	PositionType string
	Vacancies    int64
}

// Открытые вакансии по видам позиций (научная, ППС, аспирантура и постдок, управление).
func (q *Queries) LandingVacanciesByType(ctx context.Context, today time.Time) ([]LandingVacanciesByTypeRow, error) {
	rows, err := q.db.Query(ctx, landingVacanciesByType, today)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LandingVacanciesByTypeRow
	for rows.Next() {
		var i LandingVacanciesByTypeRow
		if err := rows.Scan(&i.PositionType, &i.Vacancies); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
