// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: login_attempts.sql

package dbgen

import (
	"context"
	"time"
)

const clearFailedAttemptsByEmail = `-- name: ClearFailedAttemptsByEmail :exec
DELETE FROM login_attempts WHERE email = $1 AND NOT success
`

// Успешный вход обнуляет счётчик неудач по этой почте.
func (q *Queries) ClearFailedAttemptsByEmail(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, clearFailedAttemptsByEmail, email)
	return err
}

const deleteOldLoginAttempts = `-- name: DeleteOldLoginAttempts :exec
DELETE FROM login_attempts WHERE at <= $1
`

func (q *Queries) DeleteOldLoginAttempts(ctx context.Context, at time.Time) error {
	_, err := q.db.Exec(ctx, deleteOldLoginAttempts, at)
	return err
}

const failedAttemptsByEmail = `-- name: FailedAttemptsByEmail :one
SELECT count(*)::bigint AS attempts, COALESCE(min(at), 'epoch'::timestamptz)::timestamptz AS oldest
FROM login_attempts WHERE email = $1 AND NOT success AND at > $2
`

type FailedAttemptsByEmailParams struct {
	Email string
	At    time.Time
}

type FailedAttemptsByEmailRow struct {
	Attempts int64
	Oldest   time.Time
}

// Сколько неудачных попыток по почте с момента since и когда была самая ранняя из них.
func (q *Queries) FailedAttemptsByEmail(ctx context.Context, arg FailedAttemptsByEmailParams) (FailedAttemptsByEmailRow, error) {
	row := q.db.QueryRow(ctx, failedAttemptsByEmail, arg.Email, arg.At)
	var i FailedAttemptsByEmailRow
	err := row.Scan(&i.Attempts, &i.Oldest)
	return i, err
}

const failedAttemptsByIP = `-- name: FailedAttemptsByIP :one
SELECT count(*)::bigint AS attempts, COALESCE(min(at), 'epoch'::timestamptz)::timestamptz AS oldest
FROM login_attempts WHERE ip = $1 AND NOT success AND at > $2
`

type FailedAttemptsByIPParams struct {
	Ip string
	At time.Time
}

type FailedAttemptsByIPRow struct {
	Attempts int64
	Oldest   time.Time
}

func (q *Queries) FailedAttemptsByIP(ctx context.Context, arg FailedAttemptsByIPParams) (FailedAttemptsByIPRow, error) {
	row := q.db.QueryRow(ctx, failedAttemptsByIP, arg.Ip, arg.At)
	var i FailedAttemptsByIPRow
	err := row.Scan(&i.Attempts, &i.Oldest)
	return i, err
}

const recordLoginAttempt = `-- name: RecordLoginAttempt :exec
INSERT INTO login_attempts (email, ip, success, at) VALUES ($1, $2, $3, $4)
`

type RecordLoginAttemptParams struct {
	Email   string
	Ip      string
	Success bool
	At      time.Time
}

func (q *Queries) RecordLoginAttempt(ctx context.Context, arg RecordLoginAttemptParams) error {
	_, err := q.db.Exec(ctx, recordLoginAttempt,
		arg.Email,
		arg.Ip,
		arg.Success,
		arg.At,
	)
	return err
}
