// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: matching.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addFavorite = `-- name: AddFavorite :execrows
INSERT INTO favorites (user_id, vacancy_id, created_at) VALUES ($1, $2, $3::timestamptz) ON CONFLICT (user_id, vacancy_id) DO NOTHING
`

type AddFavoriteParams struct {
	UserID    uuid.UUID
	VacancyID uuid.UUID
	Now       time.Time
}

func (q *Queries) AddFavorite(ctx context.Context, arg AddFavoriteParams) (int64, error) {
	result, err := q.db.Exec(ctx, addFavorite, arg.UserID, arg.VacancyID, arg.Now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const advanceSavedSearch = `-- name: AdvanceSavedSearch :exec
UPDATE saved_searches SET
    checked_at = $1, next_run_at = $2,
    last_sent_at = COALESCE($3::timestamptz, last_sent_at)
WHERE id = $4
`

type AdvanceSavedSearchParams struct {
	CheckedAt time.Time
	NextRunAt time.Time
	SentAt    *time.Time
	ID        uuid.UUID
}

func (q *Queries) AdvanceSavedSearch(ctx context.Context, arg AdvanceSavedSearchParams) error {
	_, err := q.db.Exec(ctx, advanceSavedSearch,
		arg.CheckedAt,
		arg.NextRunAt,
		arg.SentAt,
		arg.ID,
	)
	return err
}

const countFavorites = `-- name: CountFavorites :one
SELECT count(*) FROM favorites WHERE user_id = $1
`

func (q *Queries) CountFavorites(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countFavorites, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFavoritesWithoutDeadline = `-- name: CountFavoritesWithoutDeadline :one
SELECT count(*) FROM favorites f JOIN vacancies v ON v.id = f.vacancy_id
WHERE f.user_id = $1 AND v.status = 'published' AND v.deadline IS NULL
`

// Избранные без срока подачи (открытые): в календаре о них только число.
func (q *Queries) CountFavoritesWithoutDeadline(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countFavoritesWithoutDeadline, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSavedSearches = `-- name: CountSavedSearches :one

SELECT count(*) FROM saved_searches WHERE user_id = $1
`

// ---- сохранённые поиски ----
func (q *Queries) CountSavedSearches(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSavedSearches, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteSavedSearch = `-- name: DeleteSavedSearch :execrows
DELETE FROM saved_searches WHERE id = $1 AND user_id = $2
`

type DeleteSavedSearchParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteSavedSearch(ctx context.Context, arg DeleteSavedSearchParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSavedSearch, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMatchProfile = `-- name: GetMatchProfile :one

SELECT id, degree, academic_title, region_code FROM profiles WHERE user_id = $1
`

type GetMatchProfileRow struct {
	ID            uuid.UUID
	Degree        string
	AcademicTitle string
	RegionCode    *string
}

// ---- подбор «подходящие вам» ----
// Профиль для подбора: степень, звание, регион.
func (q *Queries) GetMatchProfile(ctx context.Context, userID uuid.UUID) (GetMatchProfileRow, error) {
	row := q.db.QueryRow(ctx, getMatchProfile, userID)
	var i GetMatchProfileRow
	err := row.Scan(
		&i.ID,
		&i.Degree,
		&i.AcademicTitle,
		&i.RegionCode,
	)
	return i, err
}

const getNotificationSettings = `-- name: GetNotificationSettings :one

SELECT email_new_vacancies, email_deadlines FROM notification_settings WHERE user_id = $1
`

type GetNotificationSettingsRow struct {
	EmailNewVacancies bool
	EmailDeadlines    bool
}

// ---- настройки писем ----
func (q *Queries) GetNotificationSettings(ctx context.Context, userID uuid.UUID) (GetNotificationSettingsRow, error) {
	row := q.db.QueryRow(ctx, getNotificationSettings, userID)
	var i GetNotificationSettingsRow
	err := row.Scan(&i.EmailNewVacancies, &i.EmailDeadlines)
	return i, err
}

const getSavedSearch = `-- name: GetSavedSearch :one
SELECT id, user_id, name, query, frequency, checked_at, next_run_at, last_sent_at, created_at, updated_at FROM saved_searches WHERE id = $1 AND user_id = $2
`

type GetSavedSearchParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetSavedSearch(ctx context.Context, arg GetSavedSearchParams) (SavedSearch, error) {
	row := q.db.QueryRow(ctx, getSavedSearch, arg.ID, arg.UserID)
	var i SavedSearch
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Query,
		&i.Frequency,
		&i.CheckedAt,
		&i.NextRunAt,
		&i.LastSentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVacancyStatusByID = `-- name: GetVacancyStatusByID :one
SELECT status FROM vacancies WHERE id = $1
`

// Статус вакансии: избранным можно сделать только публичную (опубликованную или закрытую).
func (q *Queries) GetVacancyStatusByID(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getVacancyStatusByID, id)
	var status string
	err := row.Scan(&status)
	return status, err
}

const insertReminder = `-- name: InsertReminder :execrows
INSERT INTO deadline_reminders (user_id, vacancy_id, stage, deadline, sent_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT DO NOTHING
`

type InsertReminderParams struct {
	UserID    uuid.UUID
	VacancyID uuid.UUID
	Stage     int16
	Deadline  time.Time
	Now       time.Time
}

func (q *Queries) InsertReminder(ctx context.Context, arg InsertReminderParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertReminder,
		arg.UserID,
		arg.VacancyID,
		arg.Stage,
		arg.Deadline,
		arg.Now,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertSavedSearch = `-- name: InsertSavedSearch :one
INSERT INTO saved_searches (user_id, name, query, frequency, checked_at, next_run_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $5, $5)
RETURNING id, user_id, name, query, frequency, checked_at, next_run_at, last_sent_at, created_at, updated_at
`

type InsertSavedSearchParams struct {
	UserID    uuid.UUID
	Name      string
	Query     string
	Frequency string
	Now       time.Time
	NextRunAt time.Time
}

func (q *Queries) InsertSavedSearch(ctx context.Context, arg InsertSavedSearchParams) (SavedSearch, error) {
	row := q.db.QueryRow(ctx, insertSavedSearch,
		arg.UserID,
		arg.Name,
		arg.Query,
		arg.Frequency,
		arg.Now,
		arg.NextRunAt,
	)
	var i SavedSearch
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Query,
		&i.Frequency,
		&i.CheckedAt,
		&i.NextRunAt,
		&i.LastSentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDueSavedSearches = `-- name: ListDueSavedSearches :many
SELECT id FROM saved_searches WHERE frequency <> 'off' AND next_run_at <= $1 ORDER BY next_run_at, id LIMIT $2
`

type ListDueSavedSearchesParams struct {
	Now   time.Time
	Batch int32
}

// Поиски, до которых дошла очередь. Берутся без блокировки: перед работой каждый блокируется отдельно.
func (q *Queries) ListDueSavedSearches(ctx context.Context, arg ListDueSavedSearchesParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listDueSavedSearches, arg.Now, arg.Batch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFavoriteDeadlines = `-- name: ListFavoriteDeadlines :many
SELECT v.id, v.org_id, v.unit_id, v.created_by, v.status, v.title, v.position_code, v.summary, v.description, v.requirements, v.focus, v.career_level, v.work_format, v.region_code, v.city, v.housing, v.rate_percent, v.salary_from, v.salary_to, v.contract_type, v.contract_months, v.funding_source, v.funding_note, v.degree_required, v.title_required, v.is_competition, v.deadline, v.published_at, v.closed_at, v.archived_at, v.created_at, v.updated_at, v.position_name, v.position_type, v.region_name, v.org_slug, v.org_name, v.org_kind, v.org_city, v.unit_name, f.created_at AS added_at, a.id AS application_id
FROM favorites f
JOIN vacancy_view v ON v.id = f.vacancy_id
LEFT JOIN applications a ON a.vacancy_id = v.id AND a.user_id = f.user_id AND a.status <> 'withdrawn'
WHERE f.user_id = $1 AND v.status = 'published' AND v.deadline >= $2::date
ORDER BY v.deadline, f.created_at, v.id
`

type ListFavoriteDeadlinesParams struct {
	UserID uuid.UUID
	Today  time.Time
}

type ListFavoriteDeadlinesRow struct {
	VacancyView   VacancyView
	AddedAt       time.Time
	ApplicationID *uuid.UUID
}

// Календарь сроков: избранные опубликованные вакансии, срок которых сегодня или позже.
func (q *Queries) ListFavoriteDeadlines(ctx context.Context, arg ListFavoriteDeadlinesParams) ([]ListFavoriteDeadlinesRow, error) {
	rows, err := q.db.Query(ctx, listFavoriteDeadlines, arg.UserID, arg.Today)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFavoriteDeadlinesRow
	for rows.Next() {
		var i ListFavoriteDeadlinesRow
		if err := rows.Scan(
			&i.VacancyView.ID,
			&i.VacancyView.OrgID,
			&i.VacancyView.UnitID,
			&i.VacancyView.CreatedBy,
			&i.VacancyView.Status,
			&i.VacancyView.Title,
			&i.VacancyView.PositionCode,
			&i.VacancyView.Summary,
			&i.VacancyView.Description,
			&i.VacancyView.Requirements,
			&i.VacancyView.Focus,
			&i.VacancyView.CareerLevel,
			&i.VacancyView.WorkFormat,
			&i.VacancyView.RegionCode,
			&i.VacancyView.City,
			&i.VacancyView.Housing,
			&i.VacancyView.RatePercent,
			&i.VacancyView.SalaryFrom,
			&i.VacancyView.SalaryTo,
			&i.VacancyView.ContractType,
			&i.VacancyView.ContractMonths,
			&i.VacancyView.FundingSource,
			&i.VacancyView.FundingNote,
			&i.VacancyView.DegreeRequired,
			&i.VacancyView.TitleRequired,
			&i.VacancyView.IsCompetition,
			&i.VacancyView.Deadline,
			&i.VacancyView.PublishedAt,
			&i.VacancyView.ClosedAt,
			&i.VacancyView.ArchivedAt,
			&i.VacancyView.CreatedAt,
			&i.VacancyView.UpdatedAt,
			&i.VacancyView.PositionName,
			&i.VacancyView.PositionType,
			&i.VacancyView.RegionName,
			&i.VacancyView.OrgSlug,
			&i.VacancyView.OrgName,
			&i.VacancyView.OrgKind,
			&i.VacancyView.OrgCity,
			&i.VacancyView.UnitName,
			&i.AddedAt,
			&i.ApplicationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFavoriteIDs = `-- name: ListFavoriteIDs :many
SELECT vacancy_id FROM favorites WHERE user_id = $1 ORDER BY created_at DESC, vacancy_id
`

// Номера всех избранных (для закладок в списках).
func (q *Queries) ListFavoriteIDs(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listFavoriteIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var vacancy_id uuid.UUID
		if err := rows.Scan(&vacancy_id); err != nil {
			return nil, err
		}
		items = append(items, vacancy_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFavorites = `-- name: ListFavorites :many
SELECT v.id, v.org_id, v.unit_id, v.created_by, v.status, v.title, v.position_code, v.summary, v.description, v.requirements, v.focus, v.career_level, v.work_format, v.region_code, v.city, v.housing, v.rate_percent, v.salary_from, v.salary_to, v.contract_type, v.contract_months, v.funding_source, v.funding_note, v.degree_required, v.title_required, v.is_competition, v.deadline, v.published_at, v.closed_at, v.archived_at, v.created_at, v.updated_at, v.position_name, v.position_type, v.region_name, v.org_slug, v.org_name, v.org_kind, v.org_city, v.unit_name, f.created_at AS added_at, a.id AS application_id, count(*) OVER () AS total
FROM favorites f
JOIN vacancy_view v ON v.id = f.vacancy_id
LEFT JOIN applications a ON a.vacancy_id = v.id AND a.user_id = f.user_id AND a.status <> 'withdrawn'
WHERE f.user_id = $1 AND v.status IN ('published', 'closed')
ORDER BY (v.status = 'published' AND (v.deadline IS NULL OR v.deadline >= $2::date)) DESC, f.created_at DESC, v.id
LIMIT $4 OFFSET $3
`

type ListFavoritesParams struct {
	UserID    uuid.UUID
	Today     time.Time
	RowOffset int32
	RowLimit  int32
}

type ListFavoritesRow struct {
	VacancyView   VacancyView
	AddedAt       time.Time
	ApplicationID *uuid.UUID
	Total         int64
}

// Список избранного: сначала те, на что ещё можно откликнуться, внутри групп новые добавления сверху.
// Архивные вакансии не показываются (открыть их нельзя).
func (q *Queries) ListFavorites(ctx context.Context, arg ListFavoritesParams) ([]ListFavoritesRow, error) {
	rows, err := q.db.Query(ctx, listFavorites,
		arg.UserID,
		arg.Today,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFavoritesRow
	for rows.Next() {
		var i ListFavoritesRow
		if err := rows.Scan(
			&i.VacancyView.ID,
			&i.VacancyView.OrgID,
			&i.VacancyView.UnitID,
			&i.VacancyView.CreatedBy,
			&i.VacancyView.Status,
			&i.VacancyView.Title,
			&i.VacancyView.PositionCode,
			&i.VacancyView.Summary,
			&i.VacancyView.Description,
			&i.VacancyView.Requirements,
			&i.VacancyView.Focus,
			&i.VacancyView.CareerLevel,
			&i.VacancyView.WorkFormat,
			&i.VacancyView.RegionCode,
			&i.VacancyView.City,
			&i.VacancyView.Housing,
			&i.VacancyView.RatePercent,
			&i.VacancyView.SalaryFrom,
			&i.VacancyView.SalaryTo,
			&i.VacancyView.ContractType,
			&i.VacancyView.ContractMonths,
			&i.VacancyView.FundingSource,
			&i.VacancyView.FundingNote,
			&i.VacancyView.DegreeRequired,
			&i.VacancyView.TitleRequired,
			&i.VacancyView.IsCompetition,
			&i.VacancyView.Deadline,
			&i.VacancyView.PublishedAt,
			&i.VacancyView.ClosedAt,
			&i.VacancyView.ArchivedAt,
			&i.VacancyView.CreatedAt,
			&i.VacancyView.UpdatedAt,
			&i.VacancyView.PositionName,
			&i.VacancyView.PositionType,
			&i.VacancyView.RegionName,
			&i.VacancyView.OrgSlug,
			&i.VacancyView.OrgName,
			&i.VacancyView.OrgKind,
			&i.VacancyView.OrgCity,
			&i.VacancyView.UnitName,
			&i.AddedAt,
			&i.ApplicationID,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatchCandidates = `-- name: ListMatchCandidates :many
SELECT id, org_id, unit_id, created_by, status, title, position_code, summary, description, requirements, focus, career_level, work_format, region_code, city, housing, rate_percent, salary_from, salary_to, contract_type, contract_months, funding_source, funding_note, degree_required, title_required, is_competition, deadline, published_at, closed_at, archived_at, created_at, updated_at, position_name, position_type, region_name, org_slug, org_name, org_kind, org_city, unit_name FROM vacancy_view v
WHERE v.status = 'published'
  AND (v.deadline IS NULL OR v.deadline >= $1::date)
  AND EXISTS (
        SELECT 1 FROM vacancy_specialties vs
        WHERE vs.vacancy_id = v.id AND split_part(vs.specialty_code, '.', 1) || '.' || split_part(vs.specialty_code, '.', 2) = ANY($2::text[]))
  AND NOT EXISTS (SELECT 1 FROM applications a WHERE a.vacancy_id = v.id AND a.user_id = $3 AND a.status <> 'withdrawn')
  AND NOT (v.org_id = ANY($4::uuid[]) OR (v.unit_id IS NOT NULL AND v.unit_id = ANY($5::uuid[])))
ORDER BY v.published_at DESC, v.id
LIMIT $6
`

type ListMatchCandidatesParams struct {
	Today    time.Time
	Groups   []string
	UserID   uuid.UUID
	OwnOrgs  []uuid.UUID
	OwnUnits []uuid.UUID
	Batch    int32
}

// Кандидаты в подборку: опубликованные, срок не прошёл, хотя бы одна специальность из тех же групп ВАК, нет живого
// отклика человека, не вакансии организаций, где человек сам разбирает отклики. Точные баллы считает код (matching.Score).
func (q *Queries) ListMatchCandidates(ctx context.Context, arg ListMatchCandidatesParams) ([]VacancyView, error) {
	rows, err := q.db.Query(ctx, listMatchCandidates,
		arg.Today,
		arg.Groups,
		arg.UserID,
		arg.OwnOrgs,
		arg.OwnUnits,
		arg.Batch,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VacancyView
	for rows.Next() {
		var i VacancyView
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UnitID,
			&i.CreatedBy,
			&i.Status,
			&i.Title,
			&i.PositionCode,
			&i.Summary,
			&i.Description,
			&i.Requirements,
			&i.Focus,
			&i.CareerLevel,
			&i.WorkFormat,
			&i.RegionCode,
			&i.City,
			&i.Housing,
			&i.RatePercent,
			&i.SalaryFrom,
			&i.SalaryTo,
			&i.ContractType,
			&i.ContractMonths,
			&i.FundingSource,
			&i.FundingNote,
			&i.DegreeRequired,
			&i.TitleRequired,
			&i.IsCompetition,
			&i.Deadline,
			&i.PublishedAt,
			&i.ClosedAt,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PositionName,
			&i.PositionType,
			&i.RegionName,
			&i.OrgSlug,
			&i.OrgName,
			&i.OrgKind,
			&i.OrgCity,
			&i.UnitName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProfileSpecialtyCodes = `-- name: ListProfileSpecialtyCodes :many
SELECT specialty_code FROM profile_specialties WHERE profile_id = $1
`

// Коды специальностей профиля.
func (q *Queries) ListProfileSpecialtyCodes(ctx context.Context, profileID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listProfileSpecialtyCodes, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var specialty_code string
		if err := rows.Scan(&specialty_code); err != nil {
			return nil, err
		}
		items = append(items, specialty_code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReminderCandidates = `-- name: ListReminderCandidates :many

SELECT f.user_id, v.id AS vacancy_id, v.title, v.org_name,
       COALESCE(v.deadline, $1::date)::date AS deadline, -- срок есть всегда: условие ниже; COALESCE нужен только типам
       (v.deadline - $1::date)::int AS days_left,
       (CASE WHEN v.deadline - $1::date <= 1 THEN 1 ELSE 7 END)::smallint AS stage
FROM favorites f
JOIN vacancy_view v ON v.id = f.vacancy_id
WHERE v.status = 'published' AND v.deadline >= $1::date AND v.deadline <= $2::date
  AND NOT EXISTS (SELECT 1 FROM applications a WHERE a.vacancy_id = v.id AND a.user_id = f.user_id AND a.status <> 'withdrawn')
  AND NOT EXISTS (
        SELECT 1 FROM deadline_reminders r
        WHERE r.user_id = f.user_id AND r.vacancy_id = v.id AND r.deadline = v.deadline
          AND r.stage = (CASE WHEN v.deadline - $1::date <= 1 THEN 1 ELSE 7 END))
  AND f.created_at < ((v.deadline - (CASE WHEN v.deadline - $1::date <= 1 THEN 1 ELSE 7 END)::int)::timestamp AT TIME ZONE 'Europe/Moscow')
ORDER BY v.deadline, f.created_at, f.user_id
LIMIT $3
`

type ListReminderCandidatesParams struct {
	Today   time.Time
	Horizon time.Time
	Batch   int32
}

type ListReminderCandidatesRow struct {
	UserID    uuid.UUID
	VacancyID uuid.UUID
	Title     string
	OrgName   string
	Deadline  time.Time
	DaysLeft  int32
	Stage     int16
}

// ---- напоминания о сроках ----
// Кандидаты на напоминание (D-105): избранные опубликованные вакансии со сроком в ближайшие 7 дней, на которые человек
// ещё не откликнулся. Ступень: остался день или меньше — 1, иначе 7. Напоминание этой ступени для этого срока ещё не
// уходило, и человек добавил вакансию в избранное до начала окна ступени (полночь по Москве за 1 или 7 дней до срока):
// кто добавил позже, только что сам смотрел на вакансию.
func (q *Queries) ListReminderCandidates(ctx context.Context, arg ListReminderCandidatesParams) ([]ListReminderCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listReminderCandidates, arg.Today, arg.Horizon, arg.Batch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReminderCandidatesRow
	for rows.Next() {
		var i ListReminderCandidatesRow
		if err := rows.Scan(
			&i.UserID,
			&i.VacancyID,
			&i.Title,
			&i.OrgName,
			&i.Deadline,
			&i.DaysLeft,
			&i.Stage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSavedSearches = `-- name: ListSavedSearches :many
SELECT id, user_id, name, query, frequency, checked_at, next_run_at, last_sent_at, created_at, updated_at FROM saved_searches WHERE user_id = $1 ORDER BY created_at DESC, id
`

func (q *Queries) ListSavedSearches(ctx context.Context, userID uuid.UUID) ([]SavedSearch, error) {
	rows, err := q.db.Query(ctx, listSavedSearches, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SavedSearch
	for rows.Next() {
		var i SavedSearch
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Query,
			&i.Frequency,
			&i.CheckedAt,
			&i.NextRunAt,
			&i.LastSentAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpecialtyCodesOfVacancies = `-- name: ListSpecialtyCodesOfVacancies :many
SELECT vacancy_id, specialty_code FROM vacancy_specialties WHERE vacancy_id = ANY($1::uuid[])
`

// Специальности вакансий пачкой (коды без названий).
func (q *Queries) ListSpecialtyCodesOfVacancies(ctx context.Context, ids []uuid.UUID) ([]VacancySpecialty, error) {
	rows, err := q.db.Query(ctx, listSpecialtyCodesOfVacancies, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VacancySpecialty
	for rows.Next() {
		var i VacancySpecialty
		if err := rows.Scan(&i.VacancyID, &i.SpecialtyCode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSavedSearchForRun = `-- name: LockSavedSearchForRun :one
SELECT id, user_id, name, query, frequency, checked_at, next_run_at, last_sent_at, created_at, updated_at FROM saved_searches WHERE id = $1 AND frequency <> 'off' AND next_run_at <= $2 FOR UPDATE SKIP LOCKED
`

type LockSavedSearchForRunParams struct {
	ID  uuid.UUID
	Now time.Time
}

// Блокировка поиска на время рассылки. Занятый другим запуском пропускается.
func (q *Queries) LockSavedSearchForRun(ctx context.Context, arg LockSavedSearchForRunParams) (SavedSearch, error) {
	row := q.db.QueryRow(ctx, lockSavedSearchForRun, arg.ID, arg.Now)
	var i SavedSearch
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Query,
		&i.Frequency,
		&i.CheckedAt,
		&i.NextRunAt,
		&i.LastSentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockUser = `-- name: LockUser :one


SELECT id FROM users WHERE id = $1 FOR UPDATE
`

// Избранное, сохранённые поиски, подбор, сроки, напоминания (срез 11).
// ---- избранное ----
// Блокировка строки человека на время изменения его избранного и поисков: предел числа записей не обойти двумя запросами сразу.
func (q *Queries) LockUser(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockUser, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const removeFavorite = `-- name: RemoveFavorite :execrows
DELETE FROM favorites WHERE user_id = $1 AND vacancy_id = $2
`

type RemoveFavoriteParams struct {
	UserID    uuid.UUID
	VacancyID uuid.UUID
}

func (q *Queries) RemoveFavorite(ctx context.Context, arg RemoveFavoriteParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeFavorite, arg.UserID, arg.VacancyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateSavedSearch = `-- name: UpdateSavedSearch :one
UPDATE saved_searches SET name = $1, frequency = $2, next_run_at = $3, updated_at = $4,
    checked_at = COALESCE($5::timestamptz, checked_at)
WHERE id = $6 AND user_id = $7
RETURNING id, user_id, name, query, frequency, checked_at, next_run_at, last_sent_at, created_at, updated_at
`

type UpdateSavedSearchParams struct {
	Name      string
	Frequency string
	NextRunAt time.Time
	Now       time.Time
	CheckedAt *time.Time
	ID        uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) UpdateSavedSearch(ctx context.Context, arg UpdateSavedSearchParams) (SavedSearch, error) {
	row := q.db.QueryRow(ctx, updateSavedSearch,
		arg.Name,
		arg.Frequency,
		arg.NextRunAt,
		arg.Now,
		arg.CheckedAt,
		arg.ID,
		arg.UserID,
	)
	var i SavedSearch
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Query,
		&i.Frequency,
		&i.CheckedAt,
		&i.NextRunAt,
		&i.LastSentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertNotificationSettings = `-- name: UpsertNotificationSettings :exec
INSERT INTO notification_settings (user_id, email_new_vacancies, email_deadlines, updated_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id) DO UPDATE SET
    email_new_vacancies = EXCLUDED.email_new_vacancies, email_deadlines = EXCLUDED.email_deadlines, updated_at = EXCLUDED.updated_at
`

type UpsertNotificationSettingsParams struct {
	UserID            uuid.UUID
	EmailNewVacancies bool
	EmailDeadlines    bool
	Now               time.Time
}

func (q *Queries) UpsertNotificationSettings(ctx context.Context, arg UpsertNotificationSettingsParams) error {
	_, err := q.db.Exec(ctx, upsertNotificationSettings,
		arg.UserID,
		arg.EmailNewVacancies,
		arg.EmailDeadlines,
		arg.Now,
	)
	return err
}
