// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: members.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addMember = `-- name: AddMember :exec
INSERT INTO org_members (org_id, user_id, role, joined_at) VALUES ($1, $2, $3, $4)
`

type AddMemberParams struct {
	OrgID    uuid.UUID
	UserID   uuid.UUID
	Role     string
	JoinedAt time.Time
}

func (q *Queries) AddMember(ctx context.Context, arg AddMemberParams) error {
	_, err := q.db.Exec(ctx, addMember,
		arg.OrgID,
		arg.UserID,
		arg.Role,
		arg.JoinedAt,
	)
	return err
}

const clearHeadOfUser = `-- name: ClearHeadOfUser :exec
UPDATE units SET head_user_id = NULL, updated_at = $3 WHERE org_id = $1 AND head_user_id = $2
`

type ClearHeadOfUserParams struct {
	OrgID      uuid.UUID
	HeadUserID *uuid.UUID
	UpdatedAt  time.Time
}

// Человек перестал быть сотрудником: он больше не руководит подразделениями этой организации.
func (q *Queries) ClearHeadOfUser(ctx context.Context, arg ClearHeadOfUserParams) error {
	_, err := q.db.Exec(ctx, clearHeadOfUser, arg.OrgID, arg.HeadUserID, arg.UpdatedAt)
	return err
}

const getMember = `-- name: GetMember :one
SELECT org_id, user_id, role, joined_at FROM org_members WHERE org_id = $1 AND user_id = $2
`

type GetMemberParams struct {
	OrgID  uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetMember(ctx context.Context, arg GetMemberParams) (OrgMember, error) {
	row := q.db.QueryRow(ctx, getMember, arg.OrgID, arg.UserID)
	var i OrgMember
	err := row.Scan(
		&i.OrgID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const getMemberIDByEmail = `-- name: GetMemberIDByEmail :one
SELECT m.user_id FROM org_members m JOIN users u ON u.id = m.user_id WHERE m.org_id = $1 AND u.email = $2
`

type GetMemberIDByEmailParams struct {
	OrgID uuid.UUID
	Email string
}

// Работает ли человек с этой почтой в организации.
func (q *Queries) GetMemberIDByEmail(ctx context.Context, arg GetMemberIDByEmailParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getMemberIDByEmail, arg.OrgID, arg.Email)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const listMembers = `-- name: ListMembers :many
SELECT m.user_id, m.role, m.joined_at, u.display_name, u.email::text AS email
FROM org_members m JOIN users u ON u.id = m.user_id
WHERE m.org_id = $1
ORDER BY CASE m.role WHEN 'owner' THEN 0 WHEN 'hr' THEN 1 ELSE 2 END, lower(u.display_name), m.user_id
`

type ListMembersRow struct {
	UserID      uuid.UUID
	Role        string
	JoinedAt    time.Time
	DisplayName string
	Email       string
}

// Сотрудники организации с именем и почтой (почту видит только владелец: решает сервис).
func (q *Queries) ListMembers(ctx context.Context, orgID uuid.UUID) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembersRow
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
			&i.DisplayName,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOwners = `-- name: LockOwners :many
SELECT user_id FROM org_members WHERE org_id = $1 AND role = 'owner' FOR UPDATE
`

// Владельцы с блокировкой строк: два одновременных запроса не смогут оба убрать «последнего» владельца.
func (q *Queries) LockOwners(ctx context.Context, orgID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, lockOwners, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeMember = `-- name: RemoveMember :execrows
DELETE FROM org_members WHERE org_id = $1 AND user_id = $2
`

type RemoveMemberParams struct {
	OrgID  uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) RemoveMember(ctx context.Context, arg RemoveMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeMember, arg.OrgID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setMemberRole = `-- name: SetMemberRole :execrows
UPDATE org_members SET role = $3 WHERE org_id = $1 AND user_id = $2
`

type SetMemberRoleParams struct {
	OrgID  uuid.UUID
	UserID uuid.UUID
	Role   string
}

func (q *Queries) SetMemberRole(ctx context.Context, arg SetMemberRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, setMemberRole, arg.OrgID, arg.UserID, arg.Role)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
