// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"time"

	"github.com/google/uuid"
)

type AuthToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Purpose   string
	TokenHash []byte
	CreatedAt time.Time
	ExpiresAt time.Time
	UsedAt    *time.Time
}

type OrgInvitation struct {
	ID         uuid.UUID
	OrgID      uuid.UUID
	Email      string
	Role       string
	UnitID     *uuid.UUID
	TokenHash  []byte
	InvitedBy  *uuid.UUID
	CreatedAt  time.Time
	ExpiresAt  time.Time
	AcceptedAt *time.Time
	RevokedAt  *time.Time
}

type OrgMember struct {
	OrgID    uuid.UUID
	UserID   uuid.UUID
	Role     string
	JoinedAt time.Time
}

type Organization struct {
	ID          uuid.UUID
	Slug        string
	Name        string
	Kind        string
	City        string
	Website     string
	Description string
	CreatedBy   *uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Position struct {
	Code         string
	PositionType string
	Name         string
	Sort         int16
}

type RateEvent struct {
	ID   int64
	Kind string
	Key  string
	At   time.Time
}

type ReferenceSource struct {
	Catalog   string
	Title     string
	Url       string
	Edition   string
	CheckedOn time.Time
}

type Region struct {
	Code string
	Name string
}

type ScienceField struct {
	Code string
	Name string
}

type ScienceGroup struct {
	Code      string
	FieldCode string
	Name      string
}

type Session struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	TokenHash  []byte
	CreatedAt  time.Time
	LastSeenAt time.Time
	ExpiresAt  time.Time
	UserAgent  string
	Ip         string
}

type Specialty struct {
	Code      string
	GroupCode string
	Name      string
}

type Unit struct {
	ID          uuid.UUID
	OrgID       uuid.UUID
	Name        string
	Kind        string
	Description string
	Topics      []string
	HeadUserID  *uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type User struct {
	ID                   uuid.UUID
	Email                string
	DisplayName          string
	PasswordHash         string
	EmailConfirmedAt     *time.Time
	PrivacyConsentAt     time.Time
	PrivacyPolicyVersion string
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type Vacancy struct {
	ID             uuid.UUID
	OrgID          uuid.UUID
	UnitID         *uuid.UUID
	CreatedBy      *uuid.UUID
	Status         string
	Title          string
	PositionCode   string
	Summary        string
	Description    string
	Requirements   string
	Focus          string
	CareerLevel    *int16
	WorkFormat     *string
	RegionCode     *string
	City           string
	Housing        string
	RatePercent    *int16
	SalaryFrom     *int32
	SalaryTo       *int32
	ContractType   *string
	ContractMonths *int16
	FundingSource  *string
	FundingNote    string
	DegreeRequired string
	TitleRequired  string
	IsCompetition  bool
	Deadline       *time.Time
	PublishedAt    *time.Time
	ClosedAt       *time.Time
	ArchivedAt     *time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type VacancySearch struct {
	VacancyID uuid.UUID
	Doc       interface{}
}

type VacancySpecialty struct {
	VacancyID     uuid.UUID
	SpecialtyCode string
}

type VacancyView struct {
	ID             uuid.UUID
	OrgID          uuid.UUID
	UnitID         *uuid.UUID
	CreatedBy      *uuid.UUID
	Status         string
	Title          string
	PositionCode   string
	Summary        string
	Description    string
	Requirements   string
	Focus          string
	CareerLevel    *int16
	WorkFormat     *string
	RegionCode     *string
	City           string
	Housing        string
	RatePercent    *int16
	SalaryFrom     *int32
	SalaryTo       *int32
	ContractType   *string
	ContractMonths *int16
	FundingSource  *string
	FundingNote    string
	DegreeRequired string
	TitleRequired  string
	IsCompetition  bool
	Deadline       *time.Time
	PublishedAt    *time.Time
	ClosedAt       *time.Time
	ArchivedAt     *time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
	PositionName   string
	PositionType   string
	RegionName     *string
	OrgSlug        string
	OrgName        string
	OrgKind        string
	OrgCity        string
	UnitName       *string
}
