// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Application struct {
	ID              uuid.UUID
	VacancyID       uuid.UUID
	UserID          uuid.UUID
	Status          string
	CoverLetter     string
	ContactEmail    string
	Profile         []byte
	CreatedAt       time.Time
	UpdatedAt       time.Time
	StatusChangedAt time.Time
	DecisionNote    string
	DecidedBy       *uuid.UUID
}

type ApplicationFile struct {
	ID            uuid.UUID
	ApplicationID uuid.UUID
	ReferenceID   *uuid.UUID
	Kind          string
	Name          string
	Size          int32
	Position      int16
	Data          []byte
	CreatedAt     time.Time
}

type ApplicationInvitation struct {
	ID            uuid.UUID
	ApplicationID uuid.UUID
	Kind          string
	Status        string
	Message       string
	StartsAt      *time.Time
	PlaceKind     *string
	Place         string
	ContactName   string
	ContactEmail  string
	ContactPhone  string
	AnswerAt      *time.Time
	AnswerNote    string
	AnswerContact string
	AnswerTime    string
	AnsweredAt    *time.Time
	CreatedBy     *uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type AuthToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Purpose   string
	TokenHash []byte
	CreatedAt time.Time
	ExpiresAt time.Time
	UsedAt    *time.Time
}

type DeadlineReminder struct {
	UserID    uuid.UUID
	VacancyID uuid.UUID
	Stage     int16
	Deadline  time.Time
	SentAt    time.Time
}

type Favorite struct {
	UserID    uuid.UUID
	VacancyID uuid.UUID
	CreatedAt time.Time
}

type Journal struct {
	ID        int64
	Title     string
	Publisher string
	Quartile  *int16
	Sjr       pgtype.Float4
	DataYear  int16
}

type JournalIssn struct {
	Issn      string
	JournalID int64
	Position  int16
}

type Notification struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Kind      string
	Title     string
	Body      string
	Link      string
	CreatedAt time.Time
	ReadAt    *time.Time
}

type NotificationSetting struct {
	UserID            uuid.UUID
	EmailNewVacancies bool
	EmailDeadlines    bool
	UpdatedAt         time.Time
}

type OrgInvitation struct {
	ID         uuid.UUID
	OrgID      uuid.UUID
	Email      string
	Role       string
	UnitID     *uuid.UUID
	TokenHash  []byte
	InvitedBy  *uuid.UUID
	CreatedAt  time.Time
	ExpiresAt  time.Time
	AcceptedAt *time.Time
	RevokedAt  *time.Time
}

type OrgMember struct {
	OrgID    uuid.UUID
	UserID   uuid.UUID
	Role     string
	JoinedAt time.Time
}

type Organization struct {
	ID          uuid.UUID
	Slug        string
	Name        string
	Kind        string
	City        string
	Website     string
	Description string
	CreatedBy   *uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Outbox struct {
	ID            int64
	ToEmail       string
	Subject       string
	Body          string
	CreatedAt     time.Time
	NextAttemptAt time.Time
	Attempts      int32
	LastError     string
	SentAt        *time.Time
	FailedAt      *time.Time
}

type Position struct {
	Code         string
	PositionType string
	Name         string
	Sort         int16
}

type Profile struct {
	ID                  uuid.UUID
	UserID              uuid.UUID
	Visibility          string
	OpenToOffers        bool
	Headline            string
	City                string
	RegionCode          *string
	About               string
	Degree              string
	DegreeSpecialtyCode *string
	DegreeYear          *int16
	DegreeInstitution   string
	DissertationTitle   string
	AcademicTitle       string
	AcademicTitleYear   *int16
	Orcid               string
	Spin                string
	ScopusID            string
	WosID               string
	HRsci               *int16
	HScopus             *int16
	HWos                *int16
	HScholar            *int16
	ContactEmail        string
	CreatedAt           time.Time
	UpdatedAt           time.Time
	ResearchSkills      []string
	GeneralSkills       []string
}

type ProfileItem struct {
	ID        uuid.UUID
	ProfileID uuid.UUID
	Kind      string
	SortYear  int16
	Data      []byte
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ProfileSpecialty struct {
	ProfileID     uuid.UUID
	SpecialtyCode string
}

type RateEvent struct {
	ID   int64
	Kind string
	Key  string
	At   time.Time
}

type ReferenceRequest struct {
	ID            uuid.UUID
	ApplicationID uuid.UUID
	Name          string
	Email         string
	Relation      string
	TokenHash     []byte
	Status        string
	LetterText    string
	CreatedAt     time.Time
	ExpiresAt     time.Time
	LastSentAt    time.Time
	SendCount     int16
	AnsweredAt    *time.Time
}

type ReferenceSource struct {
	Catalog   string
	Title     string
	Url       string
	Edition   string
	CheckedOn time.Time
}

type Region struct {
	Code string
	Name string
}

type SavedSearch struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Name       string
	Query      string
	Frequency  string
	CheckedAt  time.Time
	NextRunAt  time.Time
	LastSentAt *time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type ScienceField struct {
	Code string
	Name string
}

type ScienceGroup struct {
	Code      string
	FieldCode string
	Name      string
}

type Session struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	TokenHash  []byte
	CreatedAt  time.Time
	LastSeenAt time.Time
	ExpiresAt  time.Time
	UserAgent  string
	Ip         string
}

type Specialty struct {
	Code      string
	GroupCode string
	Name      string
}

type Unit struct {
	ID          uuid.UUID
	OrgID       uuid.UUID
	Name        string
	Kind        string
	Description string
	Topics      []string
	HeadUserID  *uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type User struct {
	ID                   uuid.UUID
	Email                string
	DisplayName          string
	PasswordHash         string
	EmailConfirmedAt     *time.Time
	PrivacyConsentAt     time.Time
	PrivacyPolicyVersion string
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type Vacancy struct {
	ID             uuid.UUID
	OrgID          uuid.UUID
	UnitID         *uuid.UUID
	CreatedBy      *uuid.UUID
	Status         string
	Title          string
	PositionCode   string
	Summary        string
	Description    string
	Requirements   string
	Focus          string
	CareerLevel    *int16
	WorkFormat     *string
	RegionCode     *string
	City           string
	Housing        string
	RatePercent    *int16
	SalaryFrom     *int32
	SalaryTo       *int32
	ContractType   *string
	ContractMonths *int16
	FundingSource  *string
	FundingNote    string
	DegreeRequired string
	TitleRequired  string
	IsCompetition  bool
	Deadline       *time.Time
	PublishedAt    *time.Time
	ClosedAt       *time.Time
	ArchivedAt     *time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type VacancyOffer struct {
	ID         uuid.UUID
	VacancyID  uuid.UUID
	UserID     uuid.UUID
	InvitedBy  *uuid.UUID
	Status     string
	Message    string
	AnswerNote string
	AnsweredAt *time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type VacancySearch struct {
	VacancyID uuid.UUID
	Doc       interface{}
}

type VacancySpecialty struct {
	VacancyID     uuid.UUID
	SpecialtyCode string
}

type VacancyView struct {
	ID             uuid.UUID
	OrgID          uuid.UUID
	UnitID         *uuid.UUID
	CreatedBy      *uuid.UUID
	Status         string
	Title          string
	PositionCode   string
	Summary        string
	Description    string
	Requirements   string
	Focus          string
	CareerLevel    *int16
	WorkFormat     *string
	RegionCode     *string
	City           string
	Housing        string
	RatePercent    *int16
	SalaryFrom     *int32
	SalaryTo       *int32
	ContractType   *string
	ContractMonths *int16
	FundingSource  *string
	FundingNote    string
	DegreeRequired string
	TitleRequired  string
	IsCompetition  bool
	Deadline       *time.Time
	PublishedAt    *time.Time
	ClosedAt       *time.Time
	ArchivedAt     *time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
	PositionName   string
	PositionType   string
	RegionName     *string
	OrgSlug        string
	OrgName        string
	OrgKind        string
	OrgCity        string
	UnitName       *string
}
