// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimOutbox = `-- name: ClaimOutbox :many
UPDATE outbox SET next_attempt_at = $1, attempts = attempts + 1
WHERE id IN (
    SELECT o.id FROM outbox o
    WHERE o.sent_at IS NULL AND o.failed_at IS NULL AND o.next_attempt_at <= $2
    ORDER BY o.next_attempt_at, o.id
    LIMIT $3
    FOR UPDATE SKIP LOCKED
)
RETURNING id, to_email, subject, body, attempts
`

type ClaimOutboxParams struct {
	LeaseUntil time.Time
	Now        time.Time
	Batch      int32
}

type ClaimOutboxRow struct {
	ID       int64
	ToEmail  string
	Subject  string
	Body     string
	Attempts int32
}

// Берём письма «в аренду»: пока аренда не истекла, другой отправитель их не возьмёт. Попытка засчитывается сразу.
func (q *Queries) ClaimOutbox(ctx context.Context, arg ClaimOutboxParams) ([]ClaimOutboxRow, error) {
	rows, err := q.db.Query(ctx, claimOutbox, arg.LeaseUntil, arg.Now, arg.Batch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimOutboxRow
	for rows.Next() {
		var i ClaimOutboxRow
		if err := rows.Scan(
			&i.ID,
			&i.ToEmail,
			&i.Subject,
			&i.Body,
			&i.Attempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countNotifications = `-- name: CountNotifications :one
SELECT count(*)::bigint AS total, (count(*) FILTER (WHERE read_at IS NULL))::bigint AS unread
FROM notifications WHERE user_id = $1
`

type CountNotificationsRow struct {
	Total  int64
	Unread int64
}

func (q *Queries) CountNotifications(ctx context.Context, userID uuid.UUID) (CountNotificationsRow, error) {
	row := q.db.QueryRow(ctx, countNotifications, userID)
	var i CountNotificationsRow
	err := row.Scan(&i.Total, &i.Unread)
	return i, err
}

const countOutbox = `-- name: CountOutbox :one
SELECT
    (count(*) FILTER (WHERE sent_at IS NULL AND failed_at IS NULL))::bigint AS waiting,
    (count(*) FILTER (WHERE sent_at IS NOT NULL))::bigint AS sent,
    (count(*) FILTER (WHERE failed_at IS NOT NULL))::bigint AS failed
FROM outbox
`

type CountOutboxRow struct {
	Waiting int64
	Sent    int64
	Failed  int64
}

func (q *Queries) CountOutbox(ctx context.Context) (CountOutboxRow, error) {
	row := q.db.QueryRow(ctx, countOutbox)
	var i CountOutboxRow
	err := row.Scan(&i.Waiting, &i.Sent, &i.Failed)
	return i, err
}

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT count(*)::bigint FROM notifications WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteOldOutbox = `-- name: DeleteOldOutbox :exec
DELETE FROM outbox WHERE (sent_at IS NOT NULL AND sent_at < $1) OR (failed_at IS NOT NULL AND failed_at < $2)
`

type DeleteOldOutboxParams struct {
	SentBefore   *time.Time
	FailedBefore *time.Time
}

// Старые отправленные и окончательно неудавшиеся письма больше не нужны.
func (q *Queries) DeleteOldOutbox(ctx context.Context, arg DeleteOldOutboxParams) error {
	_, err := q.db.Exec(ctx, deleteOldOutbox, arg.SentBefore, arg.FailedBefore)
	return err
}

const enqueueMail = `-- name: EnqueueMail :exec
INSERT INTO outbox (to_email, subject, body, created_at, next_attempt_at)
VALUES ($1, $2, $3, $4, $4)
`

type EnqueueMailParams struct {
	ToEmail string
	Subject string
	Body    string
	Now     time.Time
}

// Письмо на любой адрес (например рекомендателю, у которого нет аккаунта).
func (q *Queries) EnqueueMail(ctx context.Context, arg EnqueueMailParams) error {
	_, err := q.db.Exec(ctx, enqueueMail,
		arg.ToEmail,
		arg.Subject,
		arg.Body,
		arg.Now,
	)
	return err
}

const enqueueMailToUser = `-- name: EnqueueMailToUser :exec
INSERT INTO outbox (to_email, subject, body, created_at, next_attempt_at)
SELECT u.email, $1, $2, $3, $3 FROM users u WHERE u.id = $4
`

type EnqueueMailToUserParams struct {
	Subject string
	Body    string
	Now     time.Time
	UserID  uuid.UUID
}

// Письмо на почту аккаунта: адрес берётся из таблицы, чужой адрес подставить нельзя.
func (q *Queries) EnqueueMailToUser(ctx context.Context, arg EnqueueMailToUserParams) error {
	_, err := q.db.Exec(ctx, enqueueMailToUser,
		arg.Subject,
		arg.Body,
		arg.Now,
		arg.UserID,
	)
	return err
}

const insertNotification = `-- name: InsertNotification :exec

INSERT INTO notifications (user_id, kind, title, body, link, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertNotificationParams struct {
	UserID uuid.UUID
	Kind   string
	Title  string
	Body   string
	Link   string
	Now    time.Time
}

// Уведомления на сайте и очередь писем (срез 8).
func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) error {
	_, err := q.db.Exec(ctx, insertNotification,
		arg.UserID,
		arg.Kind,
		arg.Title,
		arg.Body,
		arg.Link,
		arg.Now,
	)
	return err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, kind, title, body, link, created_at, read_at
FROM notifications
WHERE user_id = $1 AND (NOT $2::boolean OR read_at IS NULL)
ORDER BY created_at DESC, id
LIMIT $4 OFFSET $3
`

type ListNotificationsParams struct {
	UserID     uuid.UUID
	UnreadOnly bool
	Off        int32
	Lim        int32
}

type ListNotificationsRow struct {
	ID        uuid.UUID
	Kind      string
	Title     string
	Body      string
	Link      string
	CreatedAt time.Time
	ReadAt    *time.Time
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]ListNotificationsRow, error) {
	rows, err := q.db.Query(ctx, listNotifications,
		arg.UserID,
		arg.UnreadOnly,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotificationsRow
	for rows.Next() {
		var i ListNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Title,
			&i.Body,
			&i.Link,
			&i.CreatedAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications SET read_at = $1::timestamptz WHERE user_id = $2 AND read_at IS NULL
`

type MarkAllNotificationsReadParams struct {
	Now    time.Time
	UserID uuid.UUID
}

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, arg MarkAllNotificationsReadParams) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, arg.Now, arg.UserID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
UPDATE notifications SET read_at = $1::timestamptz WHERE id = $2 AND user_id = $3 AND read_at IS NULL
`

type MarkNotificationReadParams struct {
	Now    time.Time
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error {
	_, err := q.db.Exec(ctx, markNotificationRead, arg.Now, arg.ID, arg.UserID)
	return err
}

const markOutboxFailed = `-- name: MarkOutboxFailed :exec
UPDATE outbox SET failed_at = $1::timestamptz, last_error = $2 WHERE id = $3
`

type MarkOutboxFailedParams struct {
	Now       time.Time
	LastError string
	ID        int64
}

func (q *Queries) MarkOutboxFailed(ctx context.Context, arg MarkOutboxFailedParams) error {
	_, err := q.db.Exec(ctx, markOutboxFailed, arg.Now, arg.LastError, arg.ID)
	return err
}

const markOutboxRetry = `-- name: MarkOutboxRetry :exec
UPDATE outbox SET next_attempt_at = $1, last_error = $2 WHERE id = $3
`

type MarkOutboxRetryParams struct {
	NextAttemptAt time.Time
	LastError     string
	ID            int64
}

func (q *Queries) MarkOutboxRetry(ctx context.Context, arg MarkOutboxRetryParams) error {
	_, err := q.db.Exec(ctx, markOutboxRetry, arg.NextAttemptAt, arg.LastError, arg.ID)
	return err
}

const markOutboxSent = `-- name: MarkOutboxSent :exec
UPDATE outbox SET sent_at = $1::timestamptz, last_error = '' WHERE id = $2
`

type MarkOutboxSentParams struct {
	Now time.Time
	ID  int64
}

func (q *Queries) MarkOutboxSent(ctx context.Context, arg MarkOutboxSentParams) error {
	_, err := q.db.Exec(ctx, markOutboxSent, arg.Now, arg.ID)
	return err
}

const notificationExists = `-- name: NotificationExists :one
SELECT EXISTS (SELECT 1 FROM notifications WHERE id = $1 AND user_id = $2)
`

type NotificationExistsParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// Отметить прочитанным можно только своё; чужое или несуществующее — 0 строк.
func (q *Queries) NotificationExists(ctx context.Context, arg NotificationExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, notificationExists, arg.ID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
