// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: offers.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const answerOffer = `-- name: AnswerOffer :execrows
UPDATE vacancy_offers SET status = $1, answer_note = $2, answered_at = $3::timestamptz, updated_at = $3
WHERE id = $4 AND user_id = $5 AND status = 'pending'
`

type AnswerOfferParams struct {
	Status string
	Note   string
	Now    time.Time
	ID     uuid.UUID
	UserID uuid.UUID
}

// Ответ учёного: срабатывает один раз, только пока приглашение ждёт ответа.
func (q *Queries) AnswerOffer(ctx context.Context, arg AnswerOfferParams) (int64, error) {
	result, err := q.db.Exec(ctx, answerOffer,
		arg.Status,
		arg.Note,
		arg.Now,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cancelOffer = `-- name: CancelOffer :execrows
UPDATE vacancy_offers SET status = 'cancelled', updated_at = $1 WHERE id = $2 AND status = 'pending'
`

type CancelOfferParams struct {
	Now time.Time
	ID  uuid.UUID
}

// Отзыв организацией: только пока ответа нет.
func (q *Queries) CancelOffer(ctx context.Context, arg CancelOfferParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelOffer, arg.Now, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countMyOffersByStatus = `-- name: CountMyOffersByStatus :many
SELECT status, count(*) AS total FROM vacancy_offers WHERE user_id = $1 AND status <> 'cancelled' GROUP BY status
`

type CountMyOffersByStatusRow struct {
	Status string
	Total  int64
}

func (q *Queries) CountMyOffersByStatus(ctx context.Context, userID uuid.UUID) ([]CountMyOffersByStatusRow, error) {
	rows, err := q.db.Query(ctx, countMyOffersByStatus, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountMyOffersByStatusRow
	for rows.Next() {
		var i CountMyOffersByStatusRow
		if err := rows.Scan(&i.Status, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countSentOffersByStatus = `-- name: CountSentOffersByStatus :many
SELECT o.status, count(*) AS total
FROM vacancy_offers o JOIN vacancy_view v ON v.id = o.vacancy_id
WHERE (v.org_id = ANY($1::uuid[]) OR v.unit_id = ANY($2::uuid[]))
  AND ($3::uuid IS NULL OR o.vacancy_id = $3::uuid)
GROUP BY o.status
`

type CountSentOffersByStatusParams struct {
	WholeOrgs []uuid.UUID
	Units     []uuid.UUID
	VacancyID *uuid.UUID
}

type CountSentOffersByStatusRow struct {
	Status string
	Total  int64
}

func (q *Queries) CountSentOffersByStatus(ctx context.Context, arg CountSentOffersByStatusParams) ([]CountSentOffersByStatusRow, error) {
	rows, err := q.db.Query(ctx, countSentOffersByStatus, arg.WholeOrgs, arg.Units, arg.VacancyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountSentOffersByStatusRow
	for rows.Next() {
		var i CountSentOffersByStatusRow
		if err := rows.Scan(&i.Status, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOffer = `-- name: GetOffer :one
SELECT o.id, o.vacancy_id, o.user_id, o.status, o.message, o.answer_note, o.answered_at, o.created_at, o.updated_at,
       u.display_name AS scientist_name, p.id AS profile_id,
       v.title AS vacancy_title, v.status AS vacancy_status, v.org_id, v.unit_id, v.org_name, v.org_slug, v.deadline,
       v.city AS vacancy_city, v.unit_name,
       a.id AS application_id
FROM vacancy_offers o
JOIN users u ON u.id = o.user_id
JOIN profiles p ON p.user_id = o.user_id
JOIN vacancy_view v ON v.id = o.vacancy_id
LEFT JOIN applications a ON a.vacancy_id = o.vacancy_id AND a.user_id = o.user_id AND a.status <> 'withdrawn'
WHERE o.id = $1
`

type GetOfferRow struct {
	ID            uuid.UUID
	VacancyID     uuid.UUID
	UserID        uuid.UUID
	Status        string
	Message       string
	AnswerNote    string
	AnsweredAt    *time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
	ScientistName string
	ProfileID     uuid.UUID
	VacancyTitle  string
	VacancyStatus string
	OrgID         uuid.UUID
	UnitID        *uuid.UUID
	OrgName       string
	OrgSlug       string
	Deadline      *time.Time
	VacancyCity   string
	UnitName      *string
	ApplicationID *uuid.UUID
}

// Приглашение с вакансией, организацией и учёным; application_id — живой отклик этого человека на эту вакансию.
func (q *Queries) GetOffer(ctx context.Context, id uuid.UUID) (GetOfferRow, error) {
	row := q.db.QueryRow(ctx, getOffer, id)
	var i GetOfferRow
	err := row.Scan(
		&i.ID,
		&i.VacancyID,
		&i.UserID,
		&i.Status,
		&i.Message,
		&i.AnswerNote,
		&i.AnsweredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ScientistName,
		&i.ProfileID,
		&i.VacancyTitle,
		&i.VacancyStatus,
		&i.OrgID,
		&i.UnitID,
		&i.OrgName,
		&i.OrgSlug,
		&i.Deadline,
		&i.VacancyCity,
		&i.UnitName,
		&i.ApplicationID,
	)
	return i, err
}

const getProfileForOffer = `-- name: GetProfileForOffer :one

SELECT p.id, p.user_id, p.visibility, u.display_name
FROM profiles p JOIN users u ON u.id = p.user_id
WHERE p.id = $1
`

type GetProfileForOfferRow struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Visibility  string
	DisplayName string
}

// Приглашения учёных на вакансии (срез 10).
// Профиль, на который хотят отправить приглашение: хозяин, режим приватности, имя.
func (q *Queries) GetProfileForOffer(ctx context.Context, id uuid.UUID) (GetProfileForOfferRow, error) {
	row := q.db.QueryRow(ctx, getProfileForOffer, id)
	var i GetProfileForOfferRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Visibility,
		&i.DisplayName,
	)
	return i, err
}

const insertOffer = `-- name: InsertOffer :one
INSERT INTO vacancy_offers (vacancy_id, user_id, invited_by, message, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $5)
RETURNING id
`

type InsertOfferParams struct {
	VacancyID uuid.UUID
	UserID    uuid.UUID
	InvitedBy *uuid.UUID
	Message   string
	Now       time.Time
}

func (q *Queries) InsertOffer(ctx context.Context, arg InsertOfferParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertOffer,
		arg.VacancyID,
		arg.UserID,
		arg.InvitedBy,
		arg.Message,
		arg.Now,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listMyOffers = `-- name: ListMyOffers :many
SELECT o.id, o.status, o.message, o.answer_note, o.answered_at, o.created_at,
       v.id AS vacancy_id, v.title AS vacancy_title, v.status AS vacancy_status, v.org_name, v.org_slug, v.deadline, v.city AS vacancy_city,
       a.id AS application_id,
       count(*) OVER () AS total
FROM vacancy_offers o
JOIN vacancy_view v ON v.id = o.vacancy_id
LEFT JOIN applications a ON a.vacancy_id = o.vacancy_id AND a.user_id = o.user_id AND a.status <> 'withdrawn'
WHERE o.user_id = $1 AND o.status <> 'cancelled'
  AND ($2::text = '' OR o.status = $2::text)
ORDER BY o.created_at DESC, o.id
LIMIT $4 OFFSET $3
`

type ListMyOffersParams struct {
	UserID    uuid.UUID
	Status    string
	RowOffset int32
	RowLimit  int32
}

type ListMyOffersRow struct {
	ID            uuid.UUID
	Status        string
	Message       string
	AnswerNote    string
	AnsweredAt    *time.Time
	CreatedAt     time.Time
	VacancyID     uuid.UUID
	VacancyTitle  string
	VacancyStatus string
	OrgName       string
	OrgSlug       string
	Deadline      *time.Time
	VacancyCity   string
	ApplicationID *uuid.UUID
	Total         int64
}

// «Мои приглашения» учёного: новые сверху; отозванные ему не показываются.
func (q *Queries) ListMyOffers(ctx context.Context, arg ListMyOffersParams) ([]ListMyOffersRow, error) {
	rows, err := q.db.Query(ctx, listMyOffers,
		arg.UserID,
		arg.Status,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMyOffersRow
	for rows.Next() {
		var i ListMyOffersRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Message,
			&i.AnswerNote,
			&i.AnsweredAt,
			&i.CreatedAt,
			&i.VacancyID,
			&i.VacancyTitle,
			&i.VacancyStatus,
			&i.OrgName,
			&i.OrgSlug,
			&i.Deadline,
			&i.VacancyCity,
			&i.ApplicationID,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOfferTargets = `-- name: ListOfferTargets :many
SELECT v.id, v.title, v.org_name, v.org_slug, v.unit_name, v.deadline,
       EXISTS (SELECT 1 FROM vacancy_offers o WHERE o.vacancy_id = v.id AND o.user_id = $1 AND o.status <> 'cancelled') AS offered,
       EXISTS (SELECT 1 FROM applications a WHERE a.vacancy_id = v.id AND a.user_id = $1 AND a.status <> 'withdrawn') AS applied
FROM vacancy_view v
WHERE v.status = 'published'
  AND (v.deadline IS NULL OR v.deadline >= $2::date)
  AND (v.org_id = ANY($3::uuid[]) OR v.unit_id = ANY($4::uuid[]))
ORDER BY lower(v.org_name), v.published_at DESC, v.id
`

type ListOfferTargetsParams struct {
	UserID    uuid.UUID
	Today     time.Time
	WholeOrgs []uuid.UUID
	Units     []uuid.UUID
}

type ListOfferTargetsRow struct {
	ID       uuid.UUID
	Title    string
	OrgName  string
	OrgSlug  string
	UnitName *string
	Deadline *time.Time
	Offered  bool
	Applied  bool
}

// Вакансии, на которые человек может пригласить этого учёного: опубликованные, срок не прошёл, в пределах прав.
// offered — уже есть живое приглашение, applied — учёный уже откликнулся.
func (q *Queries) ListOfferTargets(ctx context.Context, arg ListOfferTargetsParams) ([]ListOfferTargetsRow, error) {
	rows, err := q.db.Query(ctx, listOfferTargets,
		arg.UserID,
		arg.Today,
		arg.WholeOrgs,
		arg.Units,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOfferTargetsRow
	for rows.Next() {
		var i ListOfferTargetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.OrgName,
			&i.OrgSlug,
			&i.UnitName,
			&i.Deadline,
			&i.Offered,
			&i.Applied,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSentOffers = `-- name: ListSentOffers :many
SELECT o.id, o.status, o.message, o.answer_note, o.answered_at, o.created_at,
       u.display_name AS scientist_name, p.id AS profile_id,
       v.id AS vacancy_id, v.title AS vacancy_title, v.status AS vacancy_status, v.org_name, v.org_slug, v.unit_name,
       count(*) OVER () AS total
FROM vacancy_offers o
JOIN vacancy_view v ON v.id = o.vacancy_id
JOIN users u ON u.id = o.user_id
JOIN profiles p ON p.user_id = o.user_id
WHERE (v.org_id = ANY($1::uuid[]) OR v.unit_id = ANY($2::uuid[]))
  AND ($3::uuid IS NULL OR o.vacancy_id = $3::uuid)
  AND ($4::text = '' OR o.status = $4::text)
ORDER BY o.created_at DESC, o.id
LIMIT $6 OFFSET $5
`

type ListSentOffersParams struct {
	WholeOrgs []uuid.UUID
	Units     []uuid.UUID
	VacancyID *uuid.UUID
	Status    string
	RowOffset int32
	RowLimit  int32
}

type ListSentOffersRow struct {
	ID            uuid.UUID
	Status        string
	Message       string
	AnswerNote    string
	AnsweredAt    *time.Time
	CreatedAt     time.Time
	ScientistName string
	ProfileID     uuid.UUID
	VacancyID     uuid.UUID
	VacancyTitle  string
	VacancyStatus string
	OrgName       string
	OrgSlug       string
	UnitName      *string
	Total         int64
}

// «Отправленные приглашения» организации: по вакансиям организаций целиком (whole_orgs) и подразделений (units).
func (q *Queries) ListSentOffers(ctx context.Context, arg ListSentOffersParams) ([]ListSentOffersRow, error) {
	rows, err := q.db.Query(ctx, listSentOffers,
		arg.WholeOrgs,
		arg.Units,
		arg.VacancyID,
		arg.Status,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSentOffersRow
	for rows.Next() {
		var i ListSentOffersRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Message,
			&i.AnswerNote,
			&i.AnsweredAt,
			&i.CreatedAt,
			&i.ScientistName,
			&i.ProfileID,
			&i.VacancyID,
			&i.VacancyTitle,
			&i.VacancyStatus,
			&i.OrgName,
			&i.OrgSlug,
			&i.UnitName,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
