// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organizations.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countOrganizations = `-- name: CountOrganizations :one
SELECT count(*)::bigint
FROM organizations o
WHERE ($1::text = '' OR o.kind = $1::text)
  AND ($2::text = '' OR o.name ILIKE $2::text OR o.city ILIKE $2::text)
`

type CountOrganizationsParams struct {
	Kind    string
	Pattern string
}

func (q *Queries) CountOrganizations(ctx context.Context, arg CountOrganizationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOrganizations, arg.Kind, arg.Pattern)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (slug, name, kind, city, website, description, created_by, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $8)
ON CONFLICT (slug) DO NOTHING
RETURNING id, slug, name, kind, city, website, description, created_by, created_at, updated_at
`

type CreateOrganizationParams struct {
	Slug        string
	Name        string
	Kind        string
	City        string
	Website     string
	Description string
	CreatedBy   *uuid.UUID
	CreatedAt   time.Time
}

// Если адрес уже занят, строка не создаётся (сервис пробует следующий вариант адреса).
func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization,
		arg.Slug,
		arg.Name,
		arg.Kind,
		arg.City,
		arg.Website,
		arg.Description,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Kind,
		&i.City,
		&i.Website,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, slug, name, kind, city, website, description, created_by, created_at, updated_at FROM organizations WHERE id = $1
`

func (q *Queries) GetOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Kind,
		&i.City,
		&i.Website,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationBySlug = `-- name: GetOrganizationBySlug :one
SELECT id, slug, name, kind, city, website, description, created_by, created_at, updated_at FROM organizations WHERE slug = $1
`

func (q *Queries) GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationBySlug, slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Kind,
		&i.City,
		&i.Website,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrganizations = `-- name: ListOrganizations :many
SELECT o.id, o.slug, o.name, o.kind, o.city, o.website, o.description,
       (SELECT count(*) FROM units u WHERE u.org_id = o.id)::bigint AS unit_count
FROM organizations o
WHERE ($1::text = '' OR o.kind = $1::text)
  AND ($2::text = '' OR o.name ILIKE $2::text OR o.city ILIKE $2::text)
ORDER BY lower(o.name), o.id
LIMIT $4::int OFFSET $3::int
`

type ListOrganizationsParams struct {
	Kind      string
	Pattern   string
	RowOffset int32
	RowLimit  int32
}

type ListOrganizationsRow struct {
	ID          uuid.UUID
	Slug        string
	Name        string
	Kind        string
	City        string
	Website     string
	Description string
	UnitCount   int64
}

// Каталог: поиск по названию и городу без учёта регистра, фильтр по типу (” = любой).
func (q *Queries) ListOrganizations(ctx context.Context, arg ListOrganizationsParams) ([]ListOrganizationsRow, error) {
	rows, err := q.db.Query(ctx, listOrganizations,
		arg.Kind,
		arg.Pattern,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrganizationsRow
	for rows.Next() {
		var i ListOrganizationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Kind,
			&i.City,
			&i.Website,
			&i.Description,
			&i.UnitCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationsOfUser = `-- name: ListOrganizationsOfUser :many
SELECT o.id, o.slug, o.name, o.kind, o.city, m.role
FROM org_members m JOIN organizations o ON o.id = m.org_id
WHERE m.user_id = $1
ORDER BY lower(o.name), o.id
`

type ListOrganizationsOfUserRow struct {
	ID   uuid.UUID
	Slug string
	Name string
	Kind string
	City string
	Role string
}

// Организации человека вместе с его ролью.
func (q *Queries) ListOrganizationsOfUser(ctx context.Context, userID uuid.UUID) ([]ListOrganizationsOfUserRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationsOfUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrganizationsOfUserRow
	for rows.Next() {
		var i ListOrganizationsOfUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Kind,
			&i.City,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrganization = `-- name: UpdateOrganization :one
UPDATE organizations
SET name = $2, kind = $3, city = $4, website = $5, description = $6, updated_at = $7
WHERE id = $1
RETURNING id, slug, name, kind, city, website, description, created_by, created_at, updated_at
`

type UpdateOrganizationParams struct {
	ID          uuid.UUID
	Name        string
	Kind        string
	City        string
	Website     string
	Description string
	UpdatedAt   time.Time
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganization,
		arg.ID,
		arg.Name,
		arg.Kind,
		arg.City,
		arg.Website,
		arg.Description,
		arg.UpdatedAt,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Kind,
		&i.City,
		&i.Website,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
