// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profiles.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addProfileSpecialties = `-- name: AddProfileSpecialties :exec
INSERT INTO profile_specialties (profile_id, specialty_code) SELECT $1, unnest($2::text[])
`

type AddProfileSpecialtiesParams struct {
	ProfileID uuid.UUID
	Codes     []string
}

func (q *Queries) AddProfileSpecialties(ctx context.Context, arg AddProfileSpecialtiesParams) error {
	_, err := q.db.Exec(ctx, addProfileSpecialties, arg.ProfileID, arg.Codes)
	return err
}

const countProfileItems = `-- name: CountProfileItems :one
SELECT count(*) FROM profile_items WHERE profile_id = $1 AND kind = $2
`

type CountProfileItemsParams struct {
	ProfileID uuid.UUID
	Kind      string
}

func (q *Queries) CountProfileItems(ctx context.Context, arg CountProfileItemsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProfileItems, arg.ProfileID, arg.Kind)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteProfileItem = `-- name: DeleteProfileItem :execrows
DELETE FROM profile_items WHERE id = $1
`

func (q *Queries) DeleteProfileItem(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProfileItem, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProfileSpecialties = `-- name: DeleteProfileSpecialties :exec
DELETE FROM profile_specialties WHERE profile_id = $1
`

func (q *Queries) DeleteProfileSpecialties(ctx context.Context, profileID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProfileSpecialties, profileID)
	return err
}

const ensureProfile = `-- name: EnsureProfile :exec

INSERT INTO profiles (user_id, created_at, updated_at) VALUES ($1, $2, $2) ON CONFLICT (user_id) DO NOTHING
`

type EnsureProfileParams struct {
	UserID uuid.UUID
	Now    time.Time
}

// Профили учёных (срез 7).
// Профиль создаётся при первом обращении; повторный вызов ничего не меняет.
func (q *Queries) EnsureProfile(ctx context.Context, arg EnsureProfileParams) error {
	_, err := q.db.Exec(ctx, ensureProfile, arg.UserID, arg.Now)
	return err
}

const getProfileByID = `-- name: GetProfileByID :one
SELECT p.id, p.user_id, p.visibility, p.open_to_offers, p.headline, p.city, p.region_code, p.about, p.degree, p.degree_specialty_code, p.degree_year, p.degree_institution, p.dissertation_title, p.academic_title, p.academic_title_year, p.orcid, p.spin, p.scopus_id, p.wos_id, p.h_rsci, p.h_scopus, p.h_wos, p.h_scholar, p.contact_email, p.created_at, p.updated_at, u.display_name, r.name AS region_name, s.name AS degree_specialty_name
FROM profiles p
JOIN users u ON u.id = p.user_id
LEFT JOIN regions r ON r.code = p.region_code
LEFT JOIN specialties s ON s.code = p.degree_specialty_code
WHERE p.id = $1
`

type GetProfileByIDRow struct {
	Profile             Profile
	DisplayName         string
	RegionName          *string
	DegreeSpecialtyName *string
}

func (q *Queries) GetProfileByID(ctx context.Context, id uuid.UUID) (GetProfileByIDRow, error) {
	row := q.db.QueryRow(ctx, getProfileByID, id)
	var i GetProfileByIDRow
	err := row.Scan(
		&i.Profile.ID,
		&i.Profile.UserID,
		&i.Profile.Visibility,
		&i.Profile.OpenToOffers,
		&i.Profile.Headline,
		&i.Profile.City,
		&i.Profile.RegionCode,
		&i.Profile.About,
		&i.Profile.Degree,
		&i.Profile.DegreeSpecialtyCode,
		&i.Profile.DegreeYear,
		&i.Profile.DegreeInstitution,
		&i.Profile.DissertationTitle,
		&i.Profile.AcademicTitle,
		&i.Profile.AcademicTitleYear,
		&i.Profile.Orcid,
		&i.Profile.Spin,
		&i.Profile.ScopusID,
		&i.Profile.WosID,
		&i.Profile.HRsci,
		&i.Profile.HScopus,
		&i.Profile.HWos,
		&i.Profile.HScholar,
		&i.Profile.ContactEmail,
		&i.Profile.CreatedAt,
		&i.Profile.UpdatedAt,
		&i.DisplayName,
		&i.RegionName,
		&i.DegreeSpecialtyName,
	)
	return i, err
}

const getProfileByUser = `-- name: GetProfileByUser :one
SELECT p.id, p.user_id, p.visibility, p.open_to_offers, p.headline, p.city, p.region_code, p.about, p.degree, p.degree_specialty_code, p.degree_year, p.degree_institution, p.dissertation_title, p.academic_title, p.academic_title_year, p.orcid, p.spin, p.scopus_id, p.wos_id, p.h_rsci, p.h_scopus, p.h_wos, p.h_scholar, p.contact_email, p.created_at, p.updated_at, u.display_name, r.name AS region_name, s.name AS degree_specialty_name
FROM profiles p
JOIN users u ON u.id = p.user_id
LEFT JOIN regions r ON r.code = p.region_code
LEFT JOIN specialties s ON s.code = p.degree_specialty_code
WHERE p.user_id = $1
`

type GetProfileByUserRow struct {
	Profile             Profile
	DisplayName         string
	RegionName          *string
	DegreeSpecialtyName *string
}

func (q *Queries) GetProfileByUser(ctx context.Context, userID uuid.UUID) (GetProfileByUserRow, error) {
	row := q.db.QueryRow(ctx, getProfileByUser, userID)
	var i GetProfileByUserRow
	err := row.Scan(
		&i.Profile.ID,
		&i.Profile.UserID,
		&i.Profile.Visibility,
		&i.Profile.OpenToOffers,
		&i.Profile.Headline,
		&i.Profile.City,
		&i.Profile.RegionCode,
		&i.Profile.About,
		&i.Profile.Degree,
		&i.Profile.DegreeSpecialtyCode,
		&i.Profile.DegreeYear,
		&i.Profile.DegreeInstitution,
		&i.Profile.DissertationTitle,
		&i.Profile.AcademicTitle,
		&i.Profile.AcademicTitleYear,
		&i.Profile.Orcid,
		&i.Profile.Spin,
		&i.Profile.ScopusID,
		&i.Profile.WosID,
		&i.Profile.HRsci,
		&i.Profile.HScopus,
		&i.Profile.HWos,
		&i.Profile.HScholar,
		&i.Profile.ContactEmail,
		&i.Profile.CreatedAt,
		&i.Profile.UpdatedAt,
		&i.DisplayName,
		&i.RegionName,
		&i.DegreeSpecialtyName,
	)
	return i, err
}

const getProfileItem = `-- name: GetProfileItem :one
SELECT i.id, i.profile_id, i.kind, p.user_id FROM profile_items i JOIN profiles p ON p.id = i.profile_id WHERE i.id = $1
`

type GetProfileItemRow struct {
	ID        uuid.UUID
	ProfileID uuid.UUID
	Kind      string
	UserID    uuid.UUID
}

// Запись вместе с хозяином: так проверяем, что человек правит свою.
func (q *Queries) GetProfileItem(ctx context.Context, id uuid.UUID) (GetProfileItemRow, error) {
	row := q.db.QueryRow(ctx, getProfileItem, id)
	var i GetProfileItemRow
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Kind,
		&i.UserID,
	)
	return i, err
}

const insertProfileItem = `-- name: InsertProfileItem :one
INSERT INTO profile_items (profile_id, kind, sort_year, data, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $5) RETURNING id
`

type InsertProfileItemParams struct {
	ProfileID uuid.UUID
	Kind      string
	SortYear  int16
	Data      []byte
	Now       time.Time
}

func (q *Queries) InsertProfileItem(ctx context.Context, arg InsertProfileItemParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertProfileItem,
		arg.ProfileID,
		arg.Kind,
		arg.SortYear,
		arg.Data,
		arg.Now,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const isOrgStaff = `-- name: IsOrgStaff :one
SELECT EXISTS (SELECT 1 FROM org_members WHERE user_id = $1)
`

// Состоит ли человек хотя бы в одной организации (тогда ему виден профиль «организациям»).
func (q *Queries) IsOrgStaff(ctx context.Context, userID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isOrgStaff, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listProfileItems = `-- name: ListProfileItems :many
SELECT id, kind, data, created_at, updated_at FROM profile_items
WHERE profile_id = $1
ORDER BY kind, sort_year DESC, created_at DESC
`

type ListProfileItemsRow struct {
	ID        uuid.UUID
	Kind      string
	Data      []byte
	CreatedAt time.Time
	UpdatedAt time.Time
}

// Записи разделов: от новых к старым.
func (q *Queries) ListProfileItems(ctx context.Context, profileID uuid.UUID) ([]ListProfileItemsRow, error) {
	rows, err := q.db.Query(ctx, listProfileItems, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProfileItemsRow
	for rows.Next() {
		var i ListProfileItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Data,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProfileSpecialties = `-- name: ListProfileSpecialties :many
SELECT s.code, s.name
FROM profile_specialties ps JOIN specialties s ON s.code = ps.specialty_code
WHERE ps.profile_id = $1
ORDER BY string_to_array(s.code, '.')::int[]
`

type ListProfileSpecialtiesRow struct {
	Code string
	Name string
}

func (q *Queries) ListProfileSpecialties(ctx context.Context, profileID uuid.UUID) ([]ListProfileSpecialtiesRow, error) {
	rows, err := q.db.Query(ctx, listProfileSpecialties, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProfileSpecialtiesRow
	for rows.Next() {
		var i ListProfileSpecialtiesRow
		if err := rows.Scan(&i.Code, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockProfileByUser = `-- name: LockProfileByUser :one
SELECT id FROM profiles WHERE user_id = $1 FOR UPDATE
`

// Блокировка профиля на время правки: две одновременные правки одного профиля выстроятся в очередь.
func (q *Queries) LockProfileByUser(ctx context.Context, userID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockProfileByUser, userID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const profileHasDOI = `-- name: ProfileHasDOI :one
SELECT EXISTS (
    SELECT 1 FROM profile_items
    WHERE profile_id = $1 AND kind = 'publication' AND data ->> 'doi' = $2::text
      AND id <> $3::uuid
)
`

type ProfileHasDOIParams struct {
	ProfileID uuid.UUID
	Doi       string
	ExceptID  uuid.UUID
}

// Есть ли в профиле публикация с этим DOI (кроме записи except_id, которую как раз правят).
func (q *Queries) ProfileHasDOI(ctx context.Context, arg ProfileHasDOIParams) (bool, error) {
	row := q.db.QueryRow(ctx, profileHasDOI, arg.ProfileID, arg.Doi, arg.ExceptID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const touchProfile = `-- name: TouchProfile :exec
UPDATE profiles SET updated_at = $1 WHERE id = $2
`

type TouchProfileParams struct {
	Now time.Time
	ID  uuid.UUID
}

func (q *Queries) TouchProfile(ctx context.Context, arg TouchProfileParams) error {
	_, err := q.db.Exec(ctx, touchProfile, arg.Now, arg.ID)
	return err
}

const updateProfileCore = `-- name: UpdateProfileCore :execrows
UPDATE profiles SET
    headline = $1, city = $2, region_code = $3, about = $4,
    degree = $5, degree_specialty_code = $6, degree_year = $7,
    degree_institution = $8, dissertation_title = $9,
    academic_title = $10, academic_title_year = $11,
    orcid = $12, spin = $13, scopus_id = $14, wos_id = $15,
    h_rsci = $16, h_scopus = $17, h_wos = $18, h_scholar = $19,
    contact_email = $20, updated_at = $21
WHERE id = $22
`

type UpdateProfileCoreParams struct {
	Headline            string
	City                string
	RegionCode          *string
	About               string
	Degree              string
	DegreeSpecialtyCode *string
	DegreeYear          *int16
	DegreeInstitution   string
	DissertationTitle   string
	AcademicTitle       string
	AcademicTitleYear   *int16
	Orcid               string
	Spin                string
	ScopusID            string
	WosID               string
	HRsci               *int16
	HScopus             *int16
	HWos                *int16
	HScholar            *int16
	ContactEmail        string
	Now                 time.Time
	ID                  uuid.UUID
}

func (q *Queries) UpdateProfileCore(ctx context.Context, arg UpdateProfileCoreParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateProfileCore,
		arg.Headline,
		arg.City,
		arg.RegionCode,
		arg.About,
		arg.Degree,
		arg.DegreeSpecialtyCode,
		arg.DegreeYear,
		arg.DegreeInstitution,
		arg.DissertationTitle,
		arg.AcademicTitle,
		arg.AcademicTitleYear,
		arg.Orcid,
		arg.Spin,
		arg.ScopusID,
		arg.WosID,
		arg.HRsci,
		arg.HScopus,
		arg.HWos,
		arg.HScholar,
		arg.ContactEmail,
		arg.Now,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateProfileItem = `-- name: UpdateProfileItem :execrows
UPDATE profile_items SET sort_year = $1, data = $2, updated_at = $3 WHERE id = $4
`

type UpdateProfileItemParams struct {
	SortYear int16
	Data     []byte
	Now      time.Time
	ID       uuid.UUID
}

func (q *Queries) UpdateProfileItem(ctx context.Context, arg UpdateProfileItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateProfileItem,
		arg.SortYear,
		arg.Data,
		arg.Now,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateProfilePrivacy = `-- name: UpdateProfilePrivacy :execrows
UPDATE profiles SET visibility = $1, open_to_offers = $2, updated_at = $3 WHERE id = $4
`

type UpdateProfilePrivacyParams struct {
	Visibility   string
	OpenToOffers bool
	Now          time.Time
	ID           uuid.UUID
}

func (q *Queries) UpdateProfilePrivacy(ctx context.Context, arg UpdateProfilePrivacyParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateProfilePrivacy,
		arg.Visibility,
		arg.OpenToOffers,
		arg.Now,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
