// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rate_events.sql

package dbgen

import (
	"context"
	"time"
)

const clearRateEvents = `-- name: ClearRateEvents :exec
DELETE FROM rate_events WHERE kind = $1 AND key = $2
`

type ClearRateEventsParams struct {
	Kind string
	Key  string
}

func (q *Queries) ClearRateEvents(ctx context.Context, arg ClearRateEventsParams) error {
	_, err := q.db.Exec(ctx, clearRateEvents, arg.Kind, arg.Key)
	return err
}

const countRateEvents = `-- name: CountRateEvents :one
SELECT count(*)::bigint AS events, COALESCE(min(at), 'epoch'::timestamptz)::timestamptz AS oldest
FROM rate_events WHERE kind = $1 AND key = $2 AND at > $3
`

type CountRateEventsParams struct {
	Kind string
	Key  string
	At   time.Time
}

type CountRateEventsRow struct {
	Events int64
	Oldest time.Time
}

// Сколько событий этого вида по этому ключу после момента since и когда было самое раннее из них.
func (q *Queries) CountRateEvents(ctx context.Context, arg CountRateEventsParams) (CountRateEventsRow, error) {
	row := q.db.QueryRow(ctx, countRateEvents, arg.Kind, arg.Key, arg.At)
	var i CountRateEventsRow
	err := row.Scan(&i.Events, &i.Oldest)
	return i, err
}

const deleteOldRateEvents = `-- name: DeleteOldRateEvents :exec
DELETE FROM rate_events WHERE at <= $1
`

func (q *Queries) DeleteOldRateEvents(ctx context.Context, at time.Time) error {
	_, err := q.db.Exec(ctx, deleteOldRateEvents, at)
	return err
}

const recordRateEvent = `-- name: RecordRateEvent :exec
INSERT INTO rate_events (kind, key, at) VALUES ($1, $2, $3)
`

type RecordRateEventParams struct {
	Kind string
	Key  string
	At   time.Time
}

func (q *Queries) RecordRateEvent(ctx context.Context, arg RecordRateEventParams) error {
	_, err := q.db.Exec(ctx, recordRateEvent, arg.Kind, arg.Key, arg.At)
	return err
}
