// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reference.sql

package dbgen

import (
	"context"
)

const existingSpecialtyCodes = `-- name: ExistingSpecialtyCodes :many
SELECT code FROM specialties WHERE code = ANY($1::text[])
`

// Какие из этих кодов специальностей настоящие (остальные отбрасывает проверка).
func (q *Queries) ExistingSpecialtyCodes(ctx context.Context, dollar_1 []string) ([]string, error) {
	rows, err := q.db.Query(ctx, existingSpecialtyCodes, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var code string
		if err := rows.Scan(&code); err != nil {
			return nil, err
		}
		items = append(items, code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPosition = `-- name: GetPosition :one
SELECT code, position_type, name, sort FROM positions WHERE code = $1
`

func (q *Queries) GetPosition(ctx context.Context, code string) (Position, error) {
	row := q.db.QueryRow(ctx, getPosition, code)
	var i Position
	err := row.Scan(
		&i.Code,
		&i.PositionType,
		&i.Name,
		&i.Sort,
	)
	return i, err
}

const listPositions = `-- name: ListPositions :many
SELECT code, position_type, name, sort FROM positions ORDER BY sort
`

func (q *Queries) ListPositions(ctx context.Context) ([]Position, error) {
	rows, err := q.db.Query(ctx, listPositions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Position
	for rows.Next() {
		var i Position
		if err := rows.Scan(
			&i.Code,
			&i.PositionType,
			&i.Name,
			&i.Sort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReferenceSources = `-- name: ListReferenceSources :many
SELECT catalog, title, url, edition, checked_on FROM reference_sources ORDER BY catalog
`

func (q *Queries) ListReferenceSources(ctx context.Context) ([]ReferenceSource, error) {
	rows, err := q.db.Query(ctx, listReferenceSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReferenceSource
	for rows.Next() {
		var i ReferenceSource
		if err := rows.Scan(
			&i.Catalog,
			&i.Title,
			&i.Url,
			&i.Edition,
			&i.CheckedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegions = `-- name: ListRegions :many
SELECT code, name FROM regions ORDER BY name
`

func (q *Queries) ListRegions(ctx context.Context) ([]Region, error) {
	rows, err := q.db.Query(ctx, listRegions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Region
	for rows.Next() {
		var i Region
		if err := rows.Scan(&i.Code, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScienceFields = `-- name: ListScienceFields :many

SELECT code, name FROM science_fields ORDER BY code::int
`

// Справочники (срез 5). Порядок: по числам в коде (1.2.10 после 1.2.9), регионы по названию.
func (q *Queries) ListScienceFields(ctx context.Context) ([]ScienceField, error) {
	rows, err := q.db.Query(ctx, listScienceFields)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScienceField
	for rows.Next() {
		var i ScienceField
		if err := rows.Scan(&i.Code, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScienceGroups = `-- name: ListScienceGroups :many
SELECT code, field_code, name FROM science_groups ORDER BY string_to_array(code, '.')::int[]
`

func (q *Queries) ListScienceGroups(ctx context.Context) ([]ScienceGroup, error) {
	rows, err := q.db.Query(ctx, listScienceGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScienceGroup
	for rows.Next() {
		var i ScienceGroup
		if err := rows.Scan(&i.Code, &i.FieldCode, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpecialties = `-- name: ListSpecialties :many
SELECT code, group_code, name FROM specialties ORDER BY string_to_array(code, '.')::int[]
`

func (q *Queries) ListSpecialties(ctx context.Context) ([]Specialty, error) {
	rows, err := q.db.Query(ctx, listSpecialties)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Specialty
	for rows.Next() {
		var i Specialty
		if err := rows.Scan(&i.Code, &i.GroupCode, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const regionExists = `-- name: RegionExists :one
SELECT EXISTS (SELECT 1 FROM regions WHERE code = $1)
`

func (q *Queries) RegionExists(ctx context.Context, code string) (bool, error) {
	row := q.db.QueryRow(ctx, regionExists, code)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
