// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: references.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const answerReferenceRequest = `-- name: AnswerReferenceRequest :execrows
UPDATE reference_requests SET status = $1, letter_text = $2, answered_at = $3::timestamptz
WHERE id = $4 AND status = 'pending' AND expires_at > $3
`

type AnswerReferenceRequestParams struct {
	Status     string
	LetterText string
	Now        time.Time
	ID         uuid.UUID
}

// Ответ рекомендателя. Срабатывает один раз и только пока ссылка жива.
func (q *Queries) AnswerReferenceRequest(ctx context.Context, arg AnswerReferenceRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, answerReferenceRequest,
		arg.Status,
		arg.LetterText,
		arg.Now,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countReferenceRequests = `-- name: CountReferenceRequests :one
SELECT count(*)::bigint FROM reference_requests WHERE application_id = $1
`

func (q *Queries) CountReferenceRequests(ctx context.Context, applicationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countReferenceRequests, applicationID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteReferenceRequest = `-- name: DeleteReferenceRequest :execrows
DELETE FROM reference_requests WHERE id = $1 AND application_id = $2 AND status = 'pending'
`

type DeleteReferenceRequestParams struct {
	ID            uuid.UUID
	ApplicationID uuid.UUID
}

func (q *Queries) DeleteReferenceRequest(ctx context.Context, arg DeleteReferenceRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteReferenceRequest, arg.ID, arg.ApplicationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getReferenceByToken = `-- name: GetReferenceByToken :one
SELECT r.id, r.application_id, r.name, r.email, r.relation, r.status, r.expires_at, r.answered_at,
       a.status AS application_status, a.user_id AS applicant_id,
       u.display_name AS applicant_name,
       v.title AS vacancy_title, v.org_name, v.org_id, v.unit_id, v.id AS vacancy_id
FROM reference_requests r
JOIN applications a ON a.id = r.application_id
JOIN users u ON u.id = a.user_id
JOIN vacancy_view v ON v.id = a.vacancy_id
WHERE r.token_hash = $1
`

type GetReferenceByTokenRow struct {
	ID                uuid.UUID
	ApplicationID     uuid.UUID
	Name              string
	Email             string
	Relation          string
	Status            string
	ExpiresAt         time.Time
	AnsweredAt        *time.Time
	ApplicationStatus string
	ApplicantID       uuid.UUID
	ApplicantName     string
	VacancyTitle      string
	OrgName           string
	OrgID             uuid.UUID
	UnitID            *uuid.UUID
	VacancyID         uuid.UUID
}

// Просьба вместе с откликом, вакансией и именем соискателя (для страницы рекомендателя).
func (q *Queries) GetReferenceByToken(ctx context.Context, tokenHash []byte) (GetReferenceByTokenRow, error) {
	row := q.db.QueryRow(ctx, getReferenceByToken, tokenHash)
	var i GetReferenceByTokenRow
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Name,
		&i.Email,
		&i.Relation,
		&i.Status,
		&i.ExpiresAt,
		&i.AnsweredAt,
		&i.ApplicationStatus,
		&i.ApplicantID,
		&i.ApplicantName,
		&i.VacancyTitle,
		&i.OrgName,
		&i.OrgID,
		&i.UnitID,
		&i.VacancyID,
	)
	return i, err
}

const insertReferenceRequest = `-- name: InsertReferenceRequest :one

INSERT INTO reference_requests (application_id, name, email, relation, token_hash, created_at, expires_at, last_sent_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $6)
RETURNING id
`

type InsertReferenceRequestParams struct {
	ApplicationID uuid.UUID
	Name          string
	Email         string
	Relation      string
	TokenHash     []byte
	Now           time.Time
	ExpiresAt     time.Time
}

// Рекомендательные письма (срез 8).
func (q *Queries) InsertReferenceRequest(ctx context.Context, arg InsertReferenceRequestParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertReferenceRequest,
		arg.ApplicationID,
		arg.Name,
		arg.Email,
		arg.Relation,
		arg.TokenHash,
		arg.Now,
		arg.ExpiresAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listReferenceRequests = `-- name: ListReferenceRequests :many
SELECT id, application_id, name, email, relation, status, letter_text, created_at, expires_at, last_sent_at, send_count, answered_at
FROM reference_requests WHERE application_id = $1 ORDER BY created_at, id
`

type ListReferenceRequestsRow struct {
	ID            uuid.UUID
	ApplicationID uuid.UUID
	Name          string
	Email         string
	Relation      string
	Status        string
	LetterText    string
	CreatedAt     time.Time
	ExpiresAt     time.Time
	LastSentAt    time.Time
	SendCount     int16
	AnsweredAt    *time.Time
}

func (q *Queries) ListReferenceRequests(ctx context.Context, applicationID uuid.UUID) ([]ListReferenceRequestsRow, error) {
	rows, err := q.db.Query(ctx, listReferenceRequests, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReferenceRequestsRow
	for rows.Next() {
		var i ListReferenceRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.Name,
			&i.Email,
			&i.Relation,
			&i.Status,
			&i.LetterText,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastSentAt,
			&i.SendCount,
			&i.AnsweredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockApplication = `-- name: LockApplication :one
SELECT id FROM applications WHERE id = $1 FOR UPDATE
`

// Блокировка отклика на время изменения числа просьб.
func (q *Queries) LockApplication(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockApplication, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const lockReferenceRequest = `-- name: LockReferenceRequest :one
SELECT r.id, r.application_id, r.name, r.email, r.relation, r.status, r.expires_at, r.last_sent_at, r.send_count
FROM reference_requests r WHERE r.id = $1 AND r.application_id = $2 FOR UPDATE
`

type LockReferenceRequestParams struct {
	ID            uuid.UUID
	ApplicationID uuid.UUID
}

type LockReferenceRequestRow struct {
	ID            uuid.UUID
	ApplicationID uuid.UUID
	Name          string
	Email         string
	Relation      string
	Status        string
	ExpiresAt     time.Time
	LastSentAt    time.Time
	SendCount     int16
}

// Просьба по номеру и отклику: блокируем строку, чтобы повторная отправка и ответ не наложились.
func (q *Queries) LockReferenceRequest(ctx context.Context, arg LockReferenceRequestParams) (LockReferenceRequestRow, error) {
	row := q.db.QueryRow(ctx, lockReferenceRequest, arg.ID, arg.ApplicationID)
	var i LockReferenceRequestRow
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Name,
		&i.Email,
		&i.Relation,
		&i.Status,
		&i.ExpiresAt,
		&i.LastSentAt,
		&i.SendCount,
	)
	return i, err
}

const renewReferenceRequest = `-- name: RenewReferenceRequest :exec
UPDATE reference_requests SET token_hash = $1, expires_at = $2, last_sent_at = $3, send_count = send_count + 1
WHERE id = $4 AND status = 'pending'
`

type RenewReferenceRequestParams struct {
	TokenHash []byte
	ExpiresAt time.Time
	Now       time.Time
	ID        uuid.UUID
}

// Новая ссылка: прежняя перестаёт работать.
func (q *Queries) RenewReferenceRequest(ctx context.Context, arg RenewReferenceRequestParams) error {
	_, err := q.db.Exec(ctx, renewReferenceRequest,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.Now,
		arg.ID,
	)
	return err
}
