// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: review.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const acceptProposedTime = `-- name: AcceptProposedTime :execrows
UPDATE application_invitations SET status = 'confirmed', starts_at = answer_at, updated_at = $1::timestamptz
WHERE id = $2 AND status = 'proposed' AND answer_at > $1::timestamptz
`

type AcceptProposedTimeParams struct {
	Now time.Time
	ID  uuid.UUID
}

// Организация принимает время, которое предложил соискатель: оно становится временем собеседования.
func (q *Queries) AcceptProposedTime(ctx context.Context, arg AcceptProposedTimeParams) (int64, error) {
	result, err := q.db.Exec(ctx, acceptProposedTime, arg.Now, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const answerInvitation = `-- name: AnswerInvitation :execrows
UPDATE application_invitations
SET status = $1, answer_at = $2, answer_note = $3, answer_contact = $4, answer_time = $5,
    answered_at = $6::timestamptz, updated_at = $6::timestamptz
WHERE id = $7 AND status = 'pending'
`

type AnswerInvitationParams struct {
	ToStatus      string
	AnswerAt      *time.Time
	AnswerNote    string
	AnswerContact string
	AnswerTime    string
	Now           time.Time
	ID            uuid.UUID
}

// Ответ соискателя: срабатывает один раз, пока приглашение ждёт ответа.
func (q *Queries) AnswerInvitation(ctx context.Context, arg AnswerInvitationParams) (int64, error) {
	result, err := q.db.Exec(ctx, answerInvitation,
		arg.ToStatus,
		arg.AnswerAt,
		arg.AnswerNote,
		arg.AnswerContact,
		arg.AnswerTime,
		arg.Now,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cancelOpenInterviews = `-- name: CancelOpenInterviews :exec
UPDATE application_invitations SET status = 'cancelled', updated_at = $1::timestamptz
WHERE application_id = $2 AND kind = 'interview' AND status IN ('pending', 'proposed', 'confirmed')
`

type CancelOpenInterviewsParams struct {
	Now           time.Time
	ApplicationID uuid.UUID
}

// Новое собеседование заменяет прежние открытые.
func (q *Queries) CancelOpenInterviews(ctx context.Context, arg CancelOpenInterviewsParams) error {
	_, err := q.db.Exec(ctx, cancelOpenInterviews, arg.Now, arg.ApplicationID)
	return err
}

const cancelOpenInvitations = `-- name: CancelOpenInvitations :exec
UPDATE application_invitations SET status = 'cancelled', updated_at = $1::timestamptz
WHERE application_id = $2 AND status IN ('pending', 'proposed', 'confirmed')
`

type CancelOpenInvitationsParams struct {
	Now           time.Time
	ApplicationID uuid.UUID
}

// Все открытые приглашения отклика закрываются (отказ, отзыв отклика).
func (q *Queries) CancelOpenInvitations(ctx context.Context, arg CancelOpenInvitationsParams) error {
	_, err := q.db.Exec(ctx, cancelOpenInvitations, arg.Now, arg.ApplicationID)
	return err
}

const countCandidatesByStatus = `-- name: CountCandidatesByStatus :many
SELECT a.status, count(*)::bigint AS total
FROM applications a
JOIN vacancy_view v ON v.id = a.vacancy_id
WHERE (v.org_id = ANY($1::uuid[]) OR v.unit_id = ANY($2::uuid[]))
  AND ($3::uuid = '00000000-0000-0000-0000-000000000000'::uuid OR v.id = $3::uuid)
GROUP BY a.status
`

type CountCandidatesByStatusParams struct {
	WholeOrgs []uuid.UUID
	Units     []uuid.UUID
	VacancyID uuid.UUID
}

type CountCandidatesByStatusRow struct {
	Status string
	Total  int64
}

func (q *Queries) CountCandidatesByStatus(ctx context.Context, arg CountCandidatesByStatusParams) ([]CountCandidatesByStatusRow, error) {
	rows, err := q.db.Query(ctx, countCandidatesByStatus, arg.WholeOrgs, arg.Units, arg.VacancyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountCandidatesByStatusRow
	for rows.Next() {
		var i CountCandidatesByStatusRow
		if err := rows.Scan(&i.Status, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countInvitations = `-- name: CountInvitations :one
SELECT count(*)::bigint FROM application_invitations WHERE application_id = $1
`

func (q *Queries) CountInvitations(ctx context.Context, applicationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countInvitations, applicationID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getInvitation = `-- name: GetInvitation :one
SELECT id, application_id, kind, status, message, starts_at, place_kind, place, contact_name, contact_email, contact_phone, answer_at, answer_note, answer_contact, answer_time, answered_at, created_by, created_at, updated_at FROM application_invitations WHERE id = $1 AND application_id = $2
`

type GetInvitationParams struct {
	ID            uuid.UUID
	ApplicationID uuid.UUID
}

func (q *Queries) GetInvitation(ctx context.Context, arg GetInvitationParams) (ApplicationInvitation, error) {
	row := q.db.QueryRow(ctx, getInvitation, arg.ID, arg.ApplicationID)
	var i ApplicationInvitation
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Kind,
		&i.Status,
		&i.Message,
		&i.StartsAt,
		&i.PlaceKind,
		&i.Place,
		&i.ContactName,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.AnswerAt,
		&i.AnswerNote,
		&i.AnswerContact,
		&i.AnswerTime,
		&i.AnsweredAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertInvitation = `-- name: InsertInvitation :one


INSERT INTO application_invitations (application_id, kind, status, message, starts_at, place_kind, place, contact_name, contact_email, contact_phone, created_by, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $12)
RETURNING id
`

type InsertInvitationParams struct {
	ApplicationID uuid.UUID
	Kind          string
	Status        string
	Message       string
	StartsAt      *time.Time
	PlaceKind     *string
	Place         string
	ContactName   string
	ContactEmail  string
	ContactPhone  string
	CreatedBy     *uuid.UUID
	Now           time.Time
}

// Разбор откликов организацией (срез 9).
// Приглашения ------------------------------------------------------------------------------------------------------
func (q *Queries) InsertInvitation(ctx context.Context, arg InsertInvitationParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertInvitation,
		arg.ApplicationID,
		arg.Kind,
		arg.Status,
		arg.Message,
		arg.StartsAt,
		arg.PlaceKind,
		arg.Place,
		arg.ContactName,
		arg.ContactEmail,
		arg.ContactPhone,
		arg.CreatedBy,
		arg.Now,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listCandidateVacancies = `-- name: ListCandidateVacancies :many
SELECT v.id, v.title, v.status, v.org_name, v.org_slug,
       (count(a.id) FILTER (WHERE a.status <> 'withdrawn'))::bigint AS total,
       (count(a.id) FILTER (WHERE a.status = 'sent'))::bigint AS new_count
FROM vacancy_view v
JOIN applications a ON a.vacancy_id = v.id
WHERE v.org_id = ANY($1::uuid[]) OR v.unit_id = ANY($2::uuid[])
GROUP BY v.id, v.title, v.status, v.org_name, v.org_slug
ORDER BY max(a.created_at) DESC, v.id
LIMIT 300
`

type ListCandidateVacanciesParams struct {
	WholeOrgs []uuid.UUID
	Units     []uuid.UUID
}

type ListCandidateVacanciesRow struct {
	ID       uuid.UUID
	Title    string
	Status   string
	OrgName  string
	OrgSlug  string
	Total    int64
	NewCount int64
}

// Вакансии, на которые есть отклики: для фильтра на странице откликов и для чисел в «Моих вакансиях».
// Отозванные отклики в числа не входят.
func (q *Queries) ListCandidateVacancies(ctx context.Context, arg ListCandidateVacanciesParams) ([]ListCandidateVacanciesRow, error) {
	rows, err := q.db.Query(ctx, listCandidateVacancies, arg.WholeOrgs, arg.Units)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCandidateVacanciesRow
	for rows.Next() {
		var i ListCandidateVacanciesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.OrgName,
			&i.OrgSlug,
			&i.Total,
			&i.NewCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCandidates = `-- name: ListCandidates :many

SELECT a.id, a.status, a.created_at, a.status_changed_at,
       u.display_name AS applicant_name,
       COALESCE(a.profile->>'headline', '')::text AS headline,
       v.id AS vacancy_id, v.title AS vacancy_title, v.status AS vacancy_status, v.org_name, v.org_slug, v.unit_name,
       (SELECT count(*) FROM reference_requests r WHERE r.application_id = a.id)::bigint AS refs_total,
       (SELECT count(*) FROM reference_requests r WHERE r.application_id = a.id AND r.status = 'received')::bigint AS refs_received,
       (SELECT count(*) FROM application_invitations i WHERE i.application_id = a.id AND i.status = 'pending')::bigint AS invites_pending,
       (SELECT count(*) FROM application_invitations i WHERE i.application_id = a.id AND i.status = 'proposed')::bigint AS invites_proposed
FROM applications a
JOIN users u ON u.id = a.user_id
JOIN vacancy_view v ON v.id = a.vacancy_id
WHERE (v.org_id = ANY($1::uuid[]) OR v.unit_id = ANY($2::uuid[]))
  AND ($3::uuid = '00000000-0000-0000-0000-000000000000'::uuid OR v.id = $3::uuid)
  AND ($4::text = '' OR a.status = $4::text)
ORDER BY a.created_at DESC, a.id
LIMIT $6 OFFSET $5
`

type ListCandidatesParams struct {
	WholeOrgs []uuid.UUID
	Units     []uuid.UUID
	VacancyID uuid.UUID
	Status    string
	RowOffset int32
	RowLimit  int32
}

type ListCandidatesRow struct {
	ID              uuid.UUID
	Status          string
	CreatedAt       time.Time
	StatusChangedAt time.Time
	ApplicantName   string
	Headline        string
	VacancyID       uuid.UUID
	VacancyTitle    string
	VacancyStatus   string
	OrgName         string
	OrgSlug         string
	UnitName        *string
	RefsTotal       int64
	RefsReceived    int64
	InvitesPending  int64
	InvitesProposed int64
}

// Список откликов для организации ----------------------------------------------------------------------------------
// Отклики на вакансии, которые человек вправе разбирать: организации целиком и отдельные подразделения.
// Нулевой номер вакансии и пустой статус значат «любые».
func (q *Queries) ListCandidates(ctx context.Context, arg ListCandidatesParams) ([]ListCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listCandidates,
		arg.WholeOrgs,
		arg.Units,
		arg.VacancyID,
		arg.Status,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCandidatesRow
	for rows.Next() {
		var i ListCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.CreatedAt,
			&i.StatusChangedAt,
			&i.ApplicantName,
			&i.Headline,
			&i.VacancyID,
			&i.VacancyTitle,
			&i.VacancyStatus,
			&i.OrgName,
			&i.OrgSlug,
			&i.UnitName,
			&i.RefsTotal,
			&i.RefsReceived,
			&i.InvitesPending,
			&i.InvitesProposed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvitations = `-- name: ListInvitations :many
SELECT id, application_id, kind, status, message, starts_at, place_kind, place, contact_name, contact_email, contact_phone, answer_at, answer_note, answer_contact, answer_time, answered_at, created_by, created_at, updated_at FROM application_invitations WHERE application_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListInvitations(ctx context.Context, applicationID uuid.UUID) ([]ApplicationInvitation, error) {
	rows, err := q.db.Query(ctx, listInvitations, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApplicationInvitation
	for rows.Next() {
		var i ApplicationInvitation
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.Kind,
			&i.Status,
			&i.Message,
			&i.StartsAt,
			&i.PlaceKind,
			&i.Place,
			&i.ContactName,
			&i.ContactEmail,
			&i.ContactPhone,
			&i.AnswerAt,
			&i.AnswerNote,
			&i.AnswerContact,
			&i.AnswerTime,
			&i.AnsweredAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markApplicationInvited = `-- name: MarkApplicationInvited :execrows
UPDATE applications
SET status = 'invited', updated_at = $1::timestamptz,
    status_changed_at = CASE WHEN status = 'invited' THEN status_changed_at ELSE $1::timestamptz END
WHERE id = $2 AND status = ANY($3::text[])
`

type MarkApplicationInvitedParams struct {
	Now          time.Time
	ID           uuid.UUID
	FromStatuses []string
}

// Приглашение переводит отклик в «приглашён» (из «отправлен» и «просмотрен»; уже приглашённому только обновляет строку и тем
// самым блокирует её до конца транзакции: решение и приглашение одновременно не пройдут). Время статуса не сдвигается,
// если отклик уже был приглашён.
func (q *Queries) MarkApplicationInvited(ctx context.Context, arg MarkApplicationInvitedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markApplicationInvited, arg.Now, arg.ID, arg.FromStatuses)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setApplicationDecision = `-- name: SetApplicationDecision :execrows

UPDATE applications
SET status = $1, decision_note = $2, decided_by = $3, updated_at = $4::timestamptz, status_changed_at = $4::timestamptz
WHERE id = $5 AND status = ANY($6::text[])
`

type SetApplicationDecisionParams struct {
	ToStatus     string
	Note         string
	DecidedBy    *uuid.UUID
	Now          time.Time
	ID           uuid.UUID
	FromStatuses []string
}

// Решение организации ----------------------------------------------------------------------------------------------
// Статус меняется только из ожидаемых; записка и автор решения сохраняются вместе со статусом.
func (q *Queries) SetApplicationDecision(ctx context.Context, arg SetApplicationDecisionParams) (int64, error) {
	result, err := q.db.Exec(ctx, setApplicationDecision,
		arg.ToStatus,
		arg.Note,
		arg.DecidedBy,
		arg.Now,
		arg.ID,
		arg.FromStatuses,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setInvitationStatusFrom = `-- name: SetInvitationStatusFrom :execrows
UPDATE application_invitations SET status = $1, updated_at = $2::timestamptz
WHERE id = $3 AND status = ANY($4::text[])
`

type SetInvitationStatusFromParams struct {
	ToStatus     string
	Now          time.Time
	ID           uuid.UUID
	FromStatuses []string
}

// Статус приглашения меняется только из ожидаемых: две одновременные смены не пройдут обе.
func (q *Queries) SetInvitationStatusFrom(ctx context.Context, arg SetInvitationStatusFromParams) (int64, error) {
	result, err := q.db.Exec(ctx, setInvitationStatusFrom,
		arg.ToStatus,
		arg.Now,
		arg.ID,
		arg.FromStatuses,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
