// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: units.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUnit = `-- name: CreateUnit :one
INSERT INTO units (org_id, name, kind, description, topics, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $6)
RETURNING id, org_id, name, kind, description, topics, head_user_id, created_at, updated_at
`

type CreateUnitParams struct {
	OrgID       uuid.UUID
	Name        string
	Kind        string
	Description string
	Topics      []string
	CreatedAt   time.Time
}

func (q *Queries) CreateUnit(ctx context.Context, arg CreateUnitParams) (Unit, error) {
	row := q.db.QueryRow(ctx, createUnit,
		arg.OrgID,
		arg.Name,
		arg.Kind,
		arg.Description,
		arg.Topics,
		arg.CreatedAt,
	)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Kind,
		&i.Description,
		&i.Topics,
		&i.HeadUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUnit = `-- name: DeleteUnit :execrows
DELETE FROM units WHERE id = $1 AND org_id = $2
`

type DeleteUnitParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

func (q *Queries) DeleteUnit(ctx context.Context, arg DeleteUnitParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUnit, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUnitInOrg = `-- name: GetUnitInOrg :one
SELECT id, org_id, name, kind, description, topics, head_user_id, created_at, updated_at FROM units WHERE id = $1 AND org_id = $2
`

type GetUnitInOrgParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

func (q *Queries) GetUnitInOrg(ctx context.Context, arg GetUnitInOrgParams) (Unit, error) {
	row := q.db.QueryRow(ctx, getUnitInOrg, arg.ID, arg.OrgID)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Kind,
		&i.Description,
		&i.Topics,
		&i.HeadUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUnitWithHead = `-- name: GetUnitWithHead :one
SELECT u.id, u.org_id, u.name, u.kind, u.description, u.topics, u.head_user_id, h.display_name AS head_name
FROM units u LEFT JOIN users h ON h.id = u.head_user_id
WHERE u.id = $1 AND u.org_id = $2
`

type GetUnitWithHeadParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

type GetUnitWithHeadRow struct {
	ID          uuid.UUID
	OrgID       uuid.UUID
	Name        string
	Kind        string
	Description string
	Topics      []string
	HeadUserID  *uuid.UUID
	HeadName    *string
}

func (q *Queries) GetUnitWithHead(ctx context.Context, arg GetUnitWithHeadParams) (GetUnitWithHeadRow, error) {
	row := q.db.QueryRow(ctx, getUnitWithHead, arg.ID, arg.OrgID)
	var i GetUnitWithHeadRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Kind,
		&i.Description,
		&i.Topics,
		&i.HeadUserID,
		&i.HeadName,
	)
	return i, err
}

const listUnitIDsHeadedBy = `-- name: ListUnitIDsHeadedBy :many
SELECT id FROM units WHERE org_id = $1 AND head_user_id = $2 ORDER BY id
`

type ListUnitIDsHeadedByParams struct {
	OrgID      uuid.UUID
	HeadUserID *uuid.UUID
}

// Подразделения, которыми руководит человек.
func (q *Queries) ListUnitIDsHeadedBy(ctx context.Context, arg ListUnitIDsHeadedByParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listUnitIDsHeadedBy, arg.OrgID, arg.HeadUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnits = `-- name: ListUnits :many
SELECT u.id, u.org_id, u.name, u.kind, u.description, u.topics, u.head_user_id, h.display_name AS head_name
FROM units u LEFT JOIN users h ON h.id = u.head_user_id
WHERE u.org_id = $1
ORDER BY lower(u.name), u.id
`

type ListUnitsRow struct {
	ID          uuid.UUID
	OrgID       uuid.UUID
	Name        string
	Kind        string
	Description string
	Topics      []string
	HeadUserID  *uuid.UUID
	HeadName    *string
}

// Подразделения организации с именем руководителя.
func (q *Queries) ListUnits(ctx context.Context, orgID uuid.UUID) ([]ListUnitsRow, error) {
	rows, err := q.db.Query(ctx, listUnits, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnitsRow
	for rows.Next() {
		var i ListUnitsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Kind,
			&i.Description,
			&i.Topics,
			&i.HeadUserID,
			&i.HeadName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUnitHead = `-- name: SetUnitHead :execrows
UPDATE units SET head_user_id = $3, updated_at = $4 WHERE id = $1 AND org_id = $2
`

type SetUnitHeadParams struct {
	ID         uuid.UUID
	OrgID      uuid.UUID
	HeadUserID *uuid.UUID
	UpdatedAt  time.Time
}

func (q *Queries) SetUnitHead(ctx context.Context, arg SetUnitHeadParams) (int64, error) {
	result, err := q.db.Exec(ctx, setUnitHead,
		arg.ID,
		arg.OrgID,
		arg.HeadUserID,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setUnitHeadIfVacant = `-- name: SetUnitHeadIfVacant :execrows
UPDATE units SET head_user_id = $3, updated_at = $4 WHERE id = $1 AND org_id = $2 AND head_user_id IS NULL
`

type SetUnitHeadIfVacantParams struct {
	ID         uuid.UUID
	OrgID      uuid.UUID
	HeadUserID *uuid.UUID
	UpdatedAt  time.Time
}

// Назначить руководителя, только если места ещё никто не занимает (для принятия приглашения).
func (q *Queries) SetUnitHeadIfVacant(ctx context.Context, arg SetUnitHeadIfVacantParams) (int64, error) {
	result, err := q.db.Exec(ctx, setUnitHeadIfVacant,
		arg.ID,
		arg.OrgID,
		arg.HeadUserID,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUnit = `-- name: UpdateUnit :one
UPDATE units SET name = $3, kind = $4, description = $5, topics = $6, updated_at = $7
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, name, kind, description, topics, head_user_id, created_at, updated_at
`

type UpdateUnitParams struct {
	ID          uuid.UUID
	OrgID       uuid.UUID
	Name        string
	Kind        string
	Description string
	Topics      []string
	UpdatedAt   time.Time
}

func (q *Queries) UpdateUnit(ctx context.Context, arg UpdateUnitParams) (Unit, error) {
	row := q.db.QueryRow(ctx, updateUnit,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Kind,
		arg.Description,
		arg.Topics,
		arg.UpdatedAt,
	)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Kind,
		&i.Description,
		&i.Topics,
		&i.HeadUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
