// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const confirmUserEmail = `-- name: ConfirmUserEmail :exec
UPDATE users
SET email_confirmed_at = COALESCE(email_confirmed_at, $1::timestamptz), updated_at = $1::timestamptz
WHERE id = $2
`

type ConfirmUserEmailParams struct {
	At time.Time
	ID uuid.UUID
}

func (q *Queries) ConfirmUserEmail(ctx context.Context, arg ConfirmUserEmailParams) error {
	_, err := q.db.Exec(ctx, confirmUserEmail, arg.At, arg.ID)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, display_name, password_hash, privacy_consent_at, privacy_policy_version, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $4, $4)
ON CONFLICT (email) DO NOTHING
RETURNING id, email, display_name, password_hash, email_confirmed_at, privacy_consent_at, privacy_policy_version, created_at, updated_at
`

type CreateUserParams struct {
	Email                string
	DisplayName          string
	PasswordHash         string
	PrivacyConsentAt     time.Time
	PrivacyPolicyVersion string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.DisplayName,
		arg.PasswordHash,
		arg.PrivacyConsentAt,
		arg.PrivacyPolicyVersion,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.EmailConfirmedAt,
		&i.PrivacyConsentAt,
		&i.PrivacyPolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, display_name, password_hash, email_confirmed_at, privacy_consent_at, privacy_policy_version, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.EmailConfirmedAt,
		&i.PrivacyConsentAt,
		&i.PrivacyPolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, display_name, password_hash, email_confirmed_at, privacy_consent_at, privacy_policy_version, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.EmailConfirmedAt,
		&i.PrivacyConsentAt,
		&i.PrivacyPolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const reregisterUnconfirmedUser = `-- name: ReregisterUnconfirmedUser :one
UPDATE users
SET display_name = $2, password_hash = $3, privacy_consent_at = $4, privacy_policy_version = $5, updated_at = $4
WHERE id = $1 AND email_confirmed_at IS NULL
RETURNING id, email, display_name, password_hash, email_confirmed_at, privacy_consent_at, privacy_policy_version, created_at, updated_at
`

type ReregisterUnconfirmedUserParams struct {
	ID                   uuid.UUID
	DisplayName          string
	PasswordHash         string
	PrivacyConsentAt     time.Time
	PrivacyPolicyVersion string
}

// Повторная регистрация на непотверждённую почту: побеждает последний, кто зарегистрировался.
// Подтвердить такую почту всё равно сможет только её настоящий владелец.
func (q *Queries) ReregisterUnconfirmedUser(ctx context.Context, arg ReregisterUnconfirmedUserParams) (User, error) {
	row := q.db.QueryRow(ctx, reregisterUnconfirmedUser,
		arg.ID,
		arg.DisplayName,
		arg.PasswordHash,
		arg.PrivacyConsentAt,
		arg.PrivacyPolicyVersion,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.EmailConfirmedAt,
		&i.PrivacyConsentAt,
		&i.PrivacyPolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserName = `-- name: UpdateUserName :one
UPDATE users SET display_name = $2, updated_at = $3 WHERE id = $1 RETURNING id, email, display_name, password_hash, email_confirmed_at, privacy_consent_at, privacy_policy_version, created_at, updated_at
`

type UpdateUserNameParams struct {
	ID          uuid.UUID
	DisplayName string
	UpdatedAt   time.Time
}

func (q *Queries) UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserName, arg.ID, arg.DisplayName, arg.UpdatedAt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.EmailConfirmedAt,
		&i.PrivacyConsentAt,
		&i.PrivacyPolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $2, updated_at = $3 WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID
	PasswordHash string
	UpdatedAt    time.Time
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash, arg.UpdatedAt)
	return err
}
