// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vacancies.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addVacancySpecialties = `-- name: AddVacancySpecialties :exec
INSERT INTO vacancy_specialties (vacancy_id, specialty_code) SELECT $1, unnest($2::text[])
`

type AddVacancySpecialtiesParams struct {
	VacancyID uuid.UUID
	Codes     []string
}

func (q *Queries) AddVacancySpecialties(ctx context.Context, arg AddVacancySpecialtiesParams) error {
	_, err := q.db.Exec(ctx, addVacancySpecialties, arg.VacancyID, arg.Codes)
	return err
}

const countMyVacanciesByStatus = `-- name: CountMyVacanciesByStatus :many
SELECT status, count(*) AS total FROM vacancies
WHERE org_id = ANY($1::uuid[]) OR unit_id = ANY($2::uuid[])
GROUP BY status
`

type CountMyVacanciesByStatusParams struct {
	WholeOrgs []uuid.UUID
	Units     []uuid.UUID
}

type CountMyVacanciesByStatusRow struct {
	Status string
	Total  int64
}

func (q *Queries) CountMyVacanciesByStatus(ctx context.Context, arg CountMyVacanciesByStatusParams) ([]CountMyVacanciesByStatusRow, error) {
	rows, err := q.db.Query(ctx, countMyVacanciesByStatus, arg.WholeOrgs, arg.Units)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountMyVacanciesByStatusRow
	for rows.Next() {
		var i CountMyVacanciesByStatusRow
		if err := rows.Scan(&i.Status, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createVacancy = `-- name: CreateVacancy :one

INSERT INTO vacancies (
    org_id, unit_id, created_by, title, position_code, summary, description, requirements, focus, career_level,
    work_format, region_code, city, housing, rate_percent, salary_from, salary_to, contract_type, contract_months,
    funding_source, funding_note, degree_required, title_required, is_competition, deadline, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17, $18, $19,
    $20, $21, $22, $23, $24, $25, $26, $26
) RETURNING id
`

type CreateVacancyParams struct {
	OrgID          uuid.UUID
	UnitID         *uuid.UUID
	CreatedBy      *uuid.UUID
	Title          string
	PositionCode   string
	Summary        string
	Description    string
	Requirements   string
	Focus          string
	CareerLevel    *int16
	WorkFormat     *string
	RegionCode     *string
	City           string
	Housing        string
	RatePercent    *int16
	SalaryFrom     *int32
	SalaryTo       *int32
	ContractType   *string
	ContractMonths *int16
	FundingSource  *string
	FundingNote    string
	DegreeRequired string
	TitleRequired  string
	IsCompetition  bool
	Deadline       *time.Time
	Now            time.Time
}

// Вакансии (срез 5).
func (q *Queries) CreateVacancy(ctx context.Context, arg CreateVacancyParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createVacancy,
		arg.OrgID,
		arg.UnitID,
		arg.CreatedBy,
		arg.Title,
		arg.PositionCode,
		arg.Summary,
		arg.Description,
		arg.Requirements,
		arg.Focus,
		arg.CareerLevel,
		arg.WorkFormat,
		arg.RegionCode,
		arg.City,
		arg.Housing,
		arg.RatePercent,
		arg.SalaryFrom,
		arg.SalaryTo,
		arg.ContractType,
		arg.ContractMonths,
		arg.FundingSource,
		arg.FundingNote,
		arg.DegreeRequired,
		arg.TitleRequired,
		arg.IsCompetition,
		arg.Deadline,
		arg.Now,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteDraftVacancy = `-- name: DeleteDraftVacancy :execrows
DELETE FROM vacancies WHERE id = $1 AND status = 'draft'
`

func (q *Queries) DeleteDraftVacancy(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDraftVacancy, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteVacancySpecialties = `-- name: DeleteVacancySpecialties :exec
DELETE FROM vacancy_specialties WHERE vacancy_id = $1
`

func (q *Queries) DeleteVacancySpecialties(ctx context.Context, vacancyID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteVacancySpecialties, vacancyID)
	return err
}

const getVacancyView = `-- name: GetVacancyView :one
SELECT id, org_id, unit_id, created_by, status, title, position_code, summary, description, requirements, focus, career_level, work_format, region_code, city, housing, rate_percent, salary_from, salary_to, contract_type, contract_months, funding_source, funding_note, degree_required, title_required, is_competition, deadline, published_at, closed_at, archived_at, created_at, updated_at, position_name, position_type, region_name, org_slug, org_name, org_kind, org_city, unit_name FROM vacancy_view WHERE id = $1
`

func (q *Queries) GetVacancyView(ctx context.Context, id uuid.UUID) (VacancyView, error) {
	row := q.db.QueryRow(ctx, getVacancyView, id)
	var i VacancyView
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UnitID,
		&i.CreatedBy,
		&i.Status,
		&i.Title,
		&i.PositionCode,
		&i.Summary,
		&i.Description,
		&i.Requirements,
		&i.Focus,
		&i.CareerLevel,
		&i.WorkFormat,
		&i.RegionCode,
		&i.City,
		&i.Housing,
		&i.RatePercent,
		&i.SalaryFrom,
		&i.SalaryTo,
		&i.ContractType,
		&i.ContractMonths,
		&i.FundingSource,
		&i.FundingNote,
		&i.DegreeRequired,
		&i.TitleRequired,
		&i.IsCompetition,
		&i.Deadline,
		&i.PublishedAt,
		&i.ClosedAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PositionName,
		&i.PositionType,
		&i.RegionName,
		&i.OrgSlug,
		&i.OrgName,
		&i.OrgKind,
		&i.OrgCity,
		&i.UnitName,
	)
	return i, err
}

const listMyVacancies = `-- name: ListMyVacancies :many
SELECT id, org_id, unit_id, created_by, status, title, position_code, summary, description, requirements, focus, career_level, work_format, region_code, city, housing, rate_percent, salary_from, salary_to, contract_type, contract_months, funding_source, funding_note, degree_required, title_required, is_competition, deadline, published_at, closed_at, archived_at, created_at, updated_at, position_name, position_type, region_name, org_slug, org_name, org_kind, org_city, unit_name FROM vacancy_view
WHERE (org_id = ANY($1::uuid[]) OR unit_id = ANY($2::uuid[]))
  AND ($3::text = '' OR status = $3::text)
ORDER BY updated_at DESC, id
LIMIT $5 OFFSET $4
`

type ListMyVacanciesParams struct {
	WholeOrgs []uuid.UUID
	Units     []uuid.UUID
	Status    string
	RowOffset int32
	RowLimit  int32
}

// «Мои вакансии»: вся организация (whole_orgs) или только перечисленные подразделения (units).
func (q *Queries) ListMyVacancies(ctx context.Context, arg ListMyVacanciesParams) ([]VacancyView, error) {
	rows, err := q.db.Query(ctx, listMyVacancies,
		arg.WholeOrgs,
		arg.Units,
		arg.Status,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VacancyView
	for rows.Next() {
		var i VacancyView
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UnitID,
			&i.CreatedBy,
			&i.Status,
			&i.Title,
			&i.PositionCode,
			&i.Summary,
			&i.Description,
			&i.Requirements,
			&i.Focus,
			&i.CareerLevel,
			&i.WorkFormat,
			&i.RegionCode,
			&i.City,
			&i.Housing,
			&i.RatePercent,
			&i.SalaryFrom,
			&i.SalaryTo,
			&i.ContractType,
			&i.ContractMonths,
			&i.FundingSource,
			&i.FundingNote,
			&i.DegreeRequired,
			&i.TitleRequired,
			&i.IsCompetition,
			&i.Deadline,
			&i.PublishedAt,
			&i.ClosedAt,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PositionName,
			&i.PositionType,
			&i.RegionName,
			&i.OrgSlug,
			&i.OrgName,
			&i.OrgKind,
			&i.OrgCity,
			&i.UnitName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnitNames = `-- name: ListUnitNames :many
SELECT id, name FROM units WHERE org_id = $1 ORDER BY lower(name), id
`

type ListUnitNamesRow struct {
	ID   uuid.UUID
	Name string
}

// Подразделения организации с названиями: куда человек может поставить вакансию.
func (q *Queries) ListUnitNames(ctx context.Context, orgID uuid.UUID) ([]ListUnitNamesRow, error) {
	rows, err := q.db.Query(ctx, listUnitNames, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnitNamesRow
	for rows.Next() {
		var i ListUnitNamesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVacancySpecialties = `-- name: ListVacancySpecialties :many
SELECT vs.vacancy_id, s.code, s.name
FROM vacancy_specialties vs JOIN specialties s ON s.code = vs.specialty_code
WHERE vs.vacancy_id = ANY($1::uuid[])
ORDER BY vs.vacancy_id, string_to_array(s.code, '.')::int[]
`

type ListVacancySpecialtiesRow struct {
	VacancyID uuid.UUID
	Code      string
	Name      string
}

func (q *Queries) ListVacancySpecialties(ctx context.Context, ids []uuid.UUID) ([]ListVacancySpecialtiesRow, error) {
	rows, err := q.db.Query(ctx, listVacancySpecialties, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVacancySpecialtiesRow
	for rows.Next() {
		var i ListVacancySpecialtiesRow
		if err := rows.Scan(&i.VacancyID, &i.Code, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockVacancy = `-- name: LockVacancy :one
SELECT id, org_id, unit_id, created_by, status, title, position_code, summary, description, requirements, focus, career_level, work_format, region_code, city, housing, rate_percent, salary_from, salary_to, contract_type, contract_months, funding_source, funding_note, degree_required, title_required, is_competition, deadline, published_at, closed_at, archived_at, created_at, updated_at FROM vacancies WHERE id = $1 FOR UPDATE
`

// Строка с блокировкой: два одновременных изменения одной вакансии выстроятся в очередь.
func (q *Queries) LockVacancy(ctx context.Context, id uuid.UUID) (Vacancy, error) {
	row := q.db.QueryRow(ctx, lockVacancy, id)
	var i Vacancy
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UnitID,
		&i.CreatedBy,
		&i.Status,
		&i.Title,
		&i.PositionCode,
		&i.Summary,
		&i.Description,
		&i.Requirements,
		&i.Focus,
		&i.CareerLevel,
		&i.WorkFormat,
		&i.RegionCode,
		&i.City,
		&i.Housing,
		&i.RatePercent,
		&i.SalaryFrom,
		&i.SalaryTo,
		&i.ContractType,
		&i.ContractMonths,
		&i.FundingSource,
		&i.FundingNote,
		&i.DegreeRequired,
		&i.TitleRequired,
		&i.IsCompetition,
		&i.Deadline,
		&i.PublishedAt,
		&i.ClosedAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchVacancies = `-- name: SearchVacancies :many
SELECT v.id, v.org_id, v.unit_id, v.created_by, v.status, v.title, v.position_code, v.summary, v.description, v.requirements, v.focus, v.career_level, v.work_format, v.region_code, v.city, v.housing, v.rate_percent, v.salary_from, v.salary_to, v.contract_type, v.contract_months, v.funding_source, v.funding_note, v.degree_required, v.title_required, v.is_competition, v.deadline, v.published_at, v.closed_at, v.archived_at, v.created_at, v.updated_at, v.position_name, v.position_type, v.region_name, v.org_slug, v.org_name, v.org_kind, v.org_city, v.unit_name, count(*) OVER () AS total
FROM vacancy_view v
JOIN vacancy_search s ON s.vacancy_id = v.id
WHERE v.status = 'published'
  AND (v.deadline IS NULL OR v.deadline >= $1::date)
  AND ($2::uuid IS NULL OR v.org_id = $2::uuid)
  AND ($3::uuid IS NULL OR v.unit_id = $3::uuid)
  AND ($4::text = '' OR CASE WHEN $5::bool
         THEN word_similarity($4::text, v.title || ' ' || v.position_name || ' ' || v.org_name) >= 0.35
         ELSE s.doc @@ websearch_to_tsquery('russian', $4::text) END)
  AND (cardinality($6::text[]) = 0 OR EXISTS (
         SELECT 1 FROM vacancy_specialties vs, unnest($6::text[]) f
         WHERE vs.vacancy_id = v.id AND (vs.specialty_code = f OR vs.specialty_code LIKE f || '.%')))
  AND ($7::text = '' OR v.region_code = $7::text)
  AND (cardinality($8::text[]) = 0 OR v.work_format = ANY($8::text[]))
  AND (cardinality($9::text[]) = 0 OR v.position_type = ANY($9::text[]))
  AND (cardinality($10::int[]) = 0 OR v.career_level = ANY($10::int[]))
  AND (cardinality($11::text[]) = 0 OR v.degree_required = ANY($11::text[]))
  AND (cardinality($12::text[]) = 0 OR v.org_kind = ANY($12::text[]))
  AND (cardinality($13::text[]) = 0 OR v.funding_source = ANY($13::text[]))
  AND (cardinality($14::int[]) = 0 OR v.rate_percent = ANY($14::int[]))
  AND (cardinality($15::text[]) = 0 OR (CASE
         WHEN v.contract_type = 'permanent' THEN 'permanent'
         WHEN v.contract_months <= 12 THEN 'short'
         WHEN v.contract_months <= 36 THEN 'medium'
         WHEN v.contract_months > 36 THEN 'long'
       END) = ANY($15::text[]))
  AND ($16::int = 0 OR COALESCE(v.salary_to, v.salary_from) >= $16::int)
  AND (NOT $17::bool OR v.housing <> 'none')
  AND (NOT $18::bool OR v.is_competition)
  AND (NOT $19::bool OR v.deadline IS NULL)
  AND ($20::date IS NULL OR v.deadline <= $20::date)
ORDER BY
  CASE WHEN $21::text = 'relevance' AND $4::text <> '' THEN
    CASE WHEN $5::bool
      THEN word_similarity($4::text, v.title || ' ' || v.position_name || ' ' || v.org_name)
      ELSE ts_rank_cd(s.doc, websearch_to_tsquery('russian', $4::text)) END
  END DESC NULLS LAST,
  CASE WHEN $21::text = 'deadline' THEN v.deadline END ASC NULLS LAST,
  CASE WHEN $21::text = 'salary' THEN COALESCE(v.salary_to, v.salary_from) END DESC NULLS LAST,
  v.published_at DESC, v.id
LIMIT $23 OFFSET $22
`

type SearchVacanciesParams struct {
	Today       time.Time
	OrgID       *uuid.UUID
	UnitID      *uuid.UUID
	Q           string
	Fuzzy       bool
	Fields      []string
	Region      string
	Formats     []string
	Types       []string
	Levels      []int32
	Degrees     []string
	OrgKinds    []string
	Fundings    []string
	Rates       []int32
	Terms       []string
	SalaryMin   int32
	Housing     bool
	Competition bool
	NoDeadline  bool
	DeadlineTo  *time.Time
	Sort        string
	RowOffset   int32
	RowLimit    int32
}

type SearchVacanciesRow struct {
	VacancyView VacancyView
	Total       int64
}

// Поиск среди опубликованных вакансий (срез 6). Вакансии с прошедшим сроком подачи не показываются (today — сегодня по Москве).
// Пустой список или пустая строка у фильтра значит «любые». total — сколько всего нашлось (до LIMIT).
// fuzzy включает поиск с опечатками вместо словоформ: сервис включает его, когда точных совпадений нет.
func (q *Queries) SearchVacancies(ctx context.Context, arg SearchVacanciesParams) ([]SearchVacanciesRow, error) {
	rows, err := q.db.Query(ctx, searchVacancies,
		arg.Today,
		arg.OrgID,
		arg.UnitID,
		arg.Q,
		arg.Fuzzy,
		arg.Fields,
		arg.Region,
		arg.Formats,
		arg.Types,
		arg.Levels,
		arg.Degrees,
		arg.OrgKinds,
		arg.Fundings,
		arg.Rates,
		arg.Terms,
		arg.SalaryMin,
		arg.Housing,
		arg.Competition,
		arg.NoDeadline,
		arg.DeadlineTo,
		arg.Sort,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchVacanciesRow
	for rows.Next() {
		var i SearchVacanciesRow
		if err := rows.Scan(
			&i.VacancyView.ID,
			&i.VacancyView.OrgID,
			&i.VacancyView.UnitID,
			&i.VacancyView.CreatedBy,
			&i.VacancyView.Status,
			&i.VacancyView.Title,
			&i.VacancyView.PositionCode,
			&i.VacancyView.Summary,
			&i.VacancyView.Description,
			&i.VacancyView.Requirements,
			&i.VacancyView.Focus,
			&i.VacancyView.CareerLevel,
			&i.VacancyView.WorkFormat,
			&i.VacancyView.RegionCode,
			&i.VacancyView.City,
			&i.VacancyView.Housing,
			&i.VacancyView.RatePercent,
			&i.VacancyView.SalaryFrom,
			&i.VacancyView.SalaryTo,
			&i.VacancyView.ContractType,
			&i.VacancyView.ContractMonths,
			&i.VacancyView.FundingSource,
			&i.VacancyView.FundingNote,
			&i.VacancyView.DegreeRequired,
			&i.VacancyView.TitleRequired,
			&i.VacancyView.IsCompetition,
			&i.VacancyView.Deadline,
			&i.VacancyView.PublishedAt,
			&i.VacancyView.ClosedAt,
			&i.VacancyView.ArchivedAt,
			&i.VacancyView.CreatedAt,
			&i.VacancyView.UpdatedAt,
			&i.VacancyView.PositionName,
			&i.VacancyView.PositionType,
			&i.VacancyView.RegionName,
			&i.VacancyView.OrgSlug,
			&i.VacancyView.OrgName,
			&i.VacancyView.OrgKind,
			&i.VacancyView.OrgCity,
			&i.VacancyView.UnitName,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setVacancyStatus = `-- name: SetVacancyStatus :execrows
UPDATE vacancies SET
    status = $1,
    updated_at = $2,
    published_at = CASE WHEN $1::text = 'published' AND published_at IS NULL THEN $2 ELSE published_at END,
    closed_at = CASE WHEN $1::text = 'closed' THEN $2 ELSE closed_at END,
    archived_at = CASE WHEN $1::text = 'archived' THEN $2 ELSE archived_at END
WHERE id = $3 AND status = $4
`

type SetVacancyStatusParams struct {
	ToStatus   string
	Now        time.Time
	ID         uuid.UUID
	FromStatus string
}

// Смена статуса. Срабатывает, только если статус всё ещё from_status (кто-то мог изменить раньше).
func (q *Queries) SetVacancyStatus(ctx context.Context, arg SetVacancyStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setVacancyStatus,
		arg.ToStatus,
		arg.Now,
		arg.ID,
		arg.FromStatus,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateVacancy = `-- name: UpdateVacancy :execrows
UPDATE vacancies SET
    unit_id = $1, title = $2, position_code = $3, summary = $4, description = $5,
    requirements = $6, focus = $7, career_level = $8, work_format = $9,
    region_code = $10, city = $11, housing = $12, rate_percent = $13,
    salary_from = $14, salary_to = $15, contract_type = $16, contract_months = $17,
    funding_source = $18, funding_note = $19, degree_required = $20,
    title_required = $21, is_competition = $22, deadline = $23, updated_at = $24
WHERE id = $25
`

type UpdateVacancyParams struct {
	UnitID         *uuid.UUID
	Title          string
	PositionCode   string
	Summary        string
	Description    string
	Requirements   string
	Focus          string
	CareerLevel    *int16
	WorkFormat     *string
	RegionCode     *string
	City           string
	Housing        string
	RatePercent    *int16
	SalaryFrom     *int32
	SalaryTo       *int32
	ContractType   *string
	ContractMonths *int16
	FundingSource  *string
	FundingNote    string
	DegreeRequired string
	TitleRequired  string
	IsCompetition  bool
	Deadline       *time.Time
	Now            time.Time
	ID             uuid.UUID
}

func (q *Queries) UpdateVacancy(ctx context.Context, arg UpdateVacancyParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateVacancy,
		arg.UnitID,
		arg.Title,
		arg.PositionCode,
		arg.Summary,
		arg.Description,
		arg.Requirements,
		arg.Focus,
		arg.CareerLevel,
		arg.WorkFormat,
		arg.RegionCode,
		arg.City,
		arg.Housing,
		arg.RatePercent,
		arg.SalaryFrom,
		arg.SalaryTo,
		arg.ContractType,
		arg.ContractMonths,
		arg.FundingSource,
		arg.FundingNote,
		arg.DegreeRequired,
		arg.TitleRequired,
		arg.IsCompetition,
		arg.Deadline,
		arg.Now,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
